//-----------------------------
//-- Generated By Denny(luhox@qq.com), d:\cs4smm7.0\mysql\
//-- Remarks: dao
//-- Date Generated: 2018-07-22 21:52:14
//-----------------------------

package app.dao;

import java.util.List;
import java.util.Map;
import app.entity.*;
import org.springframework.stereotype.Repository;

@Repository("DbTableDao")
public interface DbTableDao {

	// 查询列表
	List<String> getlist(Map<String, Object> params);
	
	
	

}
