//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- Remarks: Mapper
//-- Date Generated: 2020-10-09 10:48:00
//-----------------------------

package tpa.mapper;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;
import tpa.entity.Student;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
@Repository
public interface StudentMapper extends BaseMapper<Student> {
	// 查询最大值
	Integer max(@Param("fieldname") String fieldname);

	// 按指定字段分组统计
	List<Map<String, Object>> statMapByFieldname(@Param("fieldname") String fieldname);

	// 更新计数器类型的指定字段
	void updatePlus(@Param("fieldname") String fieldname, @Param("addend") Integer addend, @Param("id") Integer id);

	List<Student> listStudentByCurriculumid(@Param("curriculumid") Integer curriculumid);

//	//根据学生学号查询学生--julius
//	Student getStudentBySno(@Param("sno")String sno);
}
