//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- entity: entity
//-- Date Generated: 2020-10-09 10:48:00
//-----------------------------

package tpa.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;

import app.entity.SuperEntity;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;
import java.math.BigDecimal;
import java.util.*;


@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
@NoArgsConstructor
@TableName("`message`")
public class Message extends SuperEntity {

	private static final long serialVersionUID = 1L;

    @TableId(value = "`id`", type = IdType.AUTO)
    private Integer id;//主键
    @TableField(value = "`from`")
    private String from;//
    @TableField(value = "`to`")
    private String to;//
    @TableField(value = "`username`")
    private String username;//姓名
    @TableField(value = "`email`")
    private String email;//邮箱
    @TableField(value = "`msg`")
    private String msg;//留言
    @TableField(value = "`create_gmt`")
    private Long create_gmt;//创建时间
    @TableField(value = "`update_gmt`")
    private Long update_gmt;//修改时间
    //加入所有字段

    public static final String ID = "id";
    public static final String FROM = "from";
    public static final String TO = "to";
    public static final String USERNAME = "username";
    public static final String EMAIL = "email";
    public static final String MSG = "msg";
    public static final String CREATE_GMT = "create_gmt";
    public static final String UPDATE_GMT = "update_gmt";

    public Message (Integer id, String from, String to, String username, String email, String msg) {
        this.id = id;
        this.from = from;
        this.to = to;
        this.username = username;
        this.email = email;
        this.msg = msg;
        this.create_gmt = new  Date().getTime();
        this.update_gmt = 0l;
    }

    public Message (String from,String to,String username,String email,String msg) {
        this.from = from;
        this.to = to;
        this.username = username;
        this.email = email;
        this.msg = msg;
        this.create_gmt = new  Date().getTime();
        this.update_gmt = 0l;
    }

    //加入公用属性
    /**
    * 创建时间
    */
    public Date getCreate_gmt_date(){
        return new Date(create_gmt); 
    }
    /**
    * 修改时间
    */
    public Date getUpdate_gmt_date(){
        return new Date(update_gmt); 
    }
}
