//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- entity: entity
//-- Date Generated: 2020-10-09 10:48:00
//-----------------------------

package tpa.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;

import app.entity.SuperEntity;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;
import java.math.BigDecimal;
import java.util.*;


@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
@NoArgsConstructor
@TableName("`student_group`")
public class Student_group extends SuperEntity {

	private static final long serialVersionUID = 1L;

    @TableId(value = "`id`", type = IdType.AUTO)
    private Integer id;//主键
    @TableField(value = "`is_actived`")
    private Boolean is_actived;//是否可以登录
    @TableField(value = "`code`")
    private String code;//分组编号，8位字符
    @TableField(value = "`name`")
    private String name;//组名
    @TableField(value = "`create_gmt`")
    private Long create_gmt;//创建时间
    @TableField(value = "`update_gmt`")
    private Long update_gmt;//修改时间
    //加入所有字段

    public static final String ID = "id";
    public static final String IS_ACTIVED = "is_actived";
    public static final String CODE = "code";
    public static final String NAME = "name";
    public static final String CREATE_GMT = "create_gmt";
    public static final String UPDATE_GMT = "update_gmt";

    public Student_group (Integer id, Boolean is_actived, String code, String name) {
        this.id = id;
        this.is_actived = is_actived;
        this.code = code;
        this.name = name;
        this.create_gmt = new  Date().getTime();
        this.update_gmt = 0l;
    }

    public Student_group (Boolean is_actived,String code,String name) {
        this.is_actived = is_actived;
        this.code = code;
        this.name = name;
        this.create_gmt = new  Date().getTime();
        this.update_gmt = 0l;
    }

    //加入公用属性
    /**
    * 创建时间
    */
    public Date getCreate_gmt_date(){
        return new Date(create_gmt); 
    }
    /**
    * 修改时间
    */
    public Date getUpdate_gmt_date(){
        return new Date(update_gmt); 
    }
}
