//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- entity: entity
//-- Date Generated: 2020-10-09 10:48:00
//-----------------------------

package tpa.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;

import app.entity.SuperEntity;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;
import java.math.BigDecimal;
import java.util.*;


@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
@NoArgsConstructor
@TableName("`syslog`")
public class Syslog extends SuperEntity {

	private static final long serialVersionUID = 1L;

    @TableId(value = "`id`", type = IdType.AUTO)
    private Integer id;//key
    @TableField(value = "`user_id`")
    private Integer user_id;//用户ID
    @TableField(value = "`user_info`")
    private String user_info;//用户标识
    @TableField(value = "`user_ip`")
    private String user_ip;//用户IP
    @TableField(value = "`spend_time`")
    private Integer spend_time;//耗时
    @TableField(value = "`request_content`")
    private String request_content;//请求内容
    @TableField(value = "`url`")
    private String url;//请求路径
    @TableField(value = "`is_attack`")
    private Boolean is_attack;//是否被判定为攻击
    @TableField(value = "`create_gmt`")
    private Long create_gmt;//创建时间
    //加入所有字段

    public static final String ID = "id";
    public static final String USER_ID = "user_id";
    public static final String USER_INFO = "user_info";
    public static final String USER_IP = "user_ip";
    public static final String SPEND_TIME = "spend_time";
    public static final String REQUEST_CONTENT = "request_content";
    public static final String URL = "url";
    public static final String IS_ATTACK = "is_attack";
    public static final String CREATE_GMT = "create_gmt";

    public Syslog (Integer id, Integer user_id, String user_info, String user_ip, Integer spend_time, String request_content, String url, Boolean is_attack) {
        this.id = id;
        this.user_id = user_id;
        this.user_info = user_info;
        this.user_ip = user_ip;
        this.spend_time = spend_time;
        this.request_content = request_content;
        this.url = url;
        this.is_attack = is_attack;
        this.create_gmt = new  Date().getTime();
    }

    public Syslog (Integer user_id,String user_info,String user_ip,Integer spend_time,String request_content,String url,Boolean is_attack) {
        this.user_id = user_id;
        this.user_info = user_info;
        this.user_ip = user_ip;
        this.spend_time = spend_time;
        this.request_content = request_content;
        this.url = url;
        this.is_attack = is_attack;
        this.create_gmt = new  Date().getTime();
    }

    //加入公用属性
    /**
    * 创建时间
    */
    public Date getCreate_gmt_date(){
        return new Date(create_gmt); 
    }
}
