//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- entity: entity
//-- Date Generated: 2020-10-09 10:48:00
//-----------------------------

package tpa.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;

import app.entity.SuperEntity;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;
import java.math.BigDecimal;
import java.util.*;


@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
@NoArgsConstructor
@TableName("`vcurriculum`")
public class Vcurriculum extends SuperEntity {

	private static final long serialVersionUID = 1L;

    @TableId(value = "`id`", type = IdType.AUTO)
    private Integer id;//课程id
    @TableField(value = "`subject_id`")
    private Integer subject_id;//学科
    @TableField(value = "`student_group_id`")
    private Integer student_group_id;//班级
    @TableField(value = "`user_id`")
    private Integer user_id;//教师
    @TableField(value = "`semester`")
    private String semester;//学期编号：2018-2019-1
    @TableField(value = "`is_actived`")
    private Boolean is_actived;//
    @TableField(value = "`subject_name`")
    private String subject_name;//科目标题
    @TableField(value = "`student_group_name`")
    private String student_group_name;//组名
    @TableField(value = "`user_name`")
    private String user_name;//姓名
    //加入所有字段

    public static final String ID = "id";
    public static final String SUBJECT_ID = "subject_id";
    public static final String STUDENT_GROUP_ID = "student_group_id";
    public static final String USER_ID = "user_id";
    public static final String SEMESTER = "semester";
    public static final String IS_ACTIVED = "is_actived";
    public static final String SUBJECT_NAME = "subject_name";
    public static final String STUDENT_GROUP_NAME = "student_group_name";
    public static final String USER_NAME = "user_name";

    public Vcurriculum (Integer id, Integer subject_id, Integer student_group_id, Integer user_id, String semester, Boolean is_actived, String subject_name, String student_group_name, String user_name) {
        this.id = id;
        this.subject_id = subject_id;
        this.student_group_id = student_group_id;
        this.user_id = user_id;
        this.semester = semester;
        this.is_actived = is_actived;
        this.subject_name = subject_name;
        this.student_group_name = student_group_name;
        this.user_name = user_name;
    }

    public Vcurriculum (Integer subject_id,Integer student_group_id,Integer user_id,String semester,Boolean is_actived,String subject_name,String student_group_name,String user_name) {
        this.subject_id = subject_id;
        this.student_group_id = student_group_id;
        this.user_id = user_id;
        this.semester = semester;
        this.is_actived = is_actived;
        this.subject_name = subject_name;
        this.student_group_name = student_group_name;
        this.user_name = user_name;
    }

    //加入公用属性
}
