//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- entity: entity
//-- Date Generated: 2020-10-09 10:48:00
//-----------------------------

package tpa.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;

import app.entity.SuperEntity;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;
import java.math.BigDecimal;
import java.util.*;


@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
@NoArgsConstructor
@TableName("`vevaluation`")
public class Vevaluation extends SuperEntity {

	private static final long serialVersionUID = 1L;

    @TableId(value = "`id`", type = IdType.AUTO)
    private Integer id;//主键
    @TableField(value = "`is_actived`")
    private Boolean is_actived;//是否启用
    @TableField(value = "`begin_gmt`")
    private Long begin_gmt;//考核开始时间
    @TableField(value = "`end_gmt`")
    private Long end_gmt;//考核关闭时间
    @TableField(value = "`content`")
    private String content;//考核内容
    @TableField(value = "`title`")
    private String title;//考核标题
    @TableField(value = "`sortid`")
    private Integer sortid;//排序id
    @TableField(value = "`curriculum_id`")
    private Integer curriculum_id;//课程id
    @TableField(value = "`create_gmt`")
    private Long create_gmt;//创建时间
    @TableField(value = "`update_gmt`")
    private Long update_gmt;//修改时间
    @TableField(value = "`subject_id`")
    private Integer subject_id;//学科
    @TableField(value = "`subject_name`")
    private String subject_name;//科目标题
    @TableField(value = "`student_group_id`")
    private Integer student_group_id;//班级
    @TableField(value = "`student_group_name`")
    private String student_group_name;//组名
    @TableField(value = "`student_group_code`")
    private String student_group_code;//分组编号，8位字符
    //加入所有字段

    public static final String ID = "id";
    public static final String IS_ACTIVED = "is_actived";
    public static final String BEGIN_GMT = "begin_gmt";
    public static final String END_GMT = "end_gmt";
    public static final String CONTENT = "content";
    public static final String TITLE = "title";
    public static final String SORTID = "sortid";
    public static final String CURRICULUM_ID = "curriculum_id";
    public static final String CREATE_GMT = "create_gmt";
    public static final String UPDATE_GMT = "update_gmt";
    public static final String SUBJECT_ID = "subject_id";
    public static final String SUBJECT_NAME = "subject_name";
    public static final String STUDENT_GROUP_ID = "student_group_id";
    public static final String STUDENT_GROUP_NAME = "student_group_name";
    public static final String STUDENT_GROUP_CODE = "student_group_code";

    public Vevaluation (Integer id, Boolean is_actived, Long begin_gmt, Long end_gmt, String content, String title, Integer sortid, Integer curriculum_id, Integer subject_id, String subject_name, Integer student_group_id, String student_group_name, String student_group_code) {
        this.id = id;
        this.is_actived = is_actived;
        this.begin_gmt = begin_gmt;
        this.end_gmt = end_gmt;
        this.content = content;
        this.title = title;
        this.sortid = sortid;
        this.curriculum_id = curriculum_id;
        this.create_gmt = new  Date().getTime();
        this.update_gmt = 0l;
        this.subject_id = subject_id;
        this.subject_name = subject_name;
        this.student_group_id = student_group_id;
        this.student_group_name = student_group_name;
        this.student_group_code = student_group_code;
    }

    public Vevaluation (Boolean is_actived,Long begin_gmt,Long end_gmt,String content,String title,Integer sortid,Integer curriculum_id,Integer subject_id,String subject_name,Integer student_group_id,String student_group_name,String student_group_code) {
        this.is_actived = is_actived;
        this.begin_gmt = begin_gmt;
        this.end_gmt = end_gmt;
        this.content = content;
        this.title = title;
        this.sortid = sortid;
        this.curriculum_id = curriculum_id;
        this.create_gmt = new  Date().getTime();
        this.update_gmt = 0l;
        this.subject_id = subject_id;
        this.subject_name = subject_name;
        this.student_group_id = student_group_id;
        this.student_group_name = student_group_name;
        this.student_group_code = student_group_code;
    }

    //加入公用属性
    /**
    * 考核开始时间
    */
    public Date getBegin_gmt_date(){
        return new Date(begin_gmt); 
    }
    /**
    * 考核关闭时间
    */
    public Date getEnd_gmt_date(){
        return new Date(end_gmt); 
    }
    /**
    * 创建时间
    */
    public Date getCreate_gmt_date(){
        return new Date(create_gmt); 
    }
    /**
    * 修改时间
    */
    public Date getUpdate_gmt_date(){
        return new Date(update_gmt); 
    }
}
