//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- entity: entity
//-- Date Generated: 2020-10-09 10:48:00
//-----------------------------

package tpa.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;

import app.entity.SuperEntity;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;
import java.math.BigDecimal;
import java.util.*;


@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
@NoArgsConstructor
@TableName("`vexperiment_record`")
public class Vexperiment_record extends SuperEntity {

	private static final long serialVersionUID = 1L;

    @TableId(value = "`id`", type = IdType.AUTO)
    private Integer id;//
    @TableField(value = "`student_id`")
    private Integer student_id;//
    @TableField(value = "`experiment_id`")
    private Integer experiment_id;//实验id
    @TableField(value = "`curriculum_id`")
    private Integer curriculum_id;//
    @TableField(value = "`truename`")
    private String truename;//用户名称
    @TableField(value = "`sno`")
    private String sno;//学号
    @TableField(value = "`sno_exp`")
    private String sno_exp;//学号
    @TableField(value = "`classcode`")
    private String classcode;//学校的班级号，不是系统内的班级号
    @TableField(value = "`score`")
    private Integer score;//实验成绩
    @TableField(value = "`student_group_is_actived`")
    private Boolean student_group_is_actived;//是否可以登录
    @TableField(value = "`student_is_actived`")
    private Boolean student_is_actived;//冻结账号
    @TableField(value = "`curriculum_is_actived`")
    private Boolean curriculum_is_actived;//
    @TableField(value = "`experiment_curriculum_is_actived`")
    private Boolean experiment_curriculum_is_actived;//
    @TableField(value = "`subject_is_actived`")
    private Boolean subject_is_actived;//是否显示
    @TableField(value = "`student_group_code`")
    private String student_group_code;//分组编号，8位字符
    @TableField(value = "`student_group_name`")
    private String student_group_name;//组名
    @TableField(value = "`comment`")
    private String comment;//对实验报告的评语，100字以内！
    @TableField(value = "`mainflow`")
    private String mainflow;//实验主要流程、基本操作或核心代码、算法片段
    @TableField(value = "`report`")
    private String report;//实验报告，用xml记录实验结果
    @TableField(value = "`result`")
    private String result;//实验结果的分析与评价
    @TableField(value = "`submit`")
    private Long submit;//实验提交时间
    @TableField(value = "`scorescript`")
    private String scorescript;//成绩描述：优秀/良好/中等/及格/不及格
    @TableField(value = "`create_gmt`")
    private Long create_gmt;//创建时间
    @TableField(value = "`update_gmt`")
    private Long update_gmt;//修改时间
    @TableField(value = "`wechat_openid`")
    private String wechat_openid;//微信openid
    @TableField(value = "`experiment_title`")
    private String experiment_title;//实验标题
    @TableField(value = "`experiment_content`")
    private String experiment_content;//实验内容
    @TableField(value = "`experiment_purposes_requirement`")
    private String experiment_purposes_requirement;//实验目的及要求
    @TableField(value = "`subject_name`")
    private String subject_name;//科目标题
    @TableField(value = "`subject_id`")
    private Integer subject_id;//学科
    @TableField(value = "`user_id`")
    private Integer user_id;//教师
    @TableField(value = "`closing_gmt`")
    private Long closing_gmt;//
    @TableField(value = "`opening_gmt`")
    private Long opening_gmt;//
    @TableField(value = "`curriculum_student_groupid`")
    private Integer curriculum_student_groupid;//班级
    @TableField(value = "`student_group_id`")
    private Integer student_group_id;//分组id
    @TableField(value = "`reviewstate`")
    private Integer reviewstate;//评阅状态1已评,2待评
    @TableField(value = "`experiment_curriculumid`")
    private Integer experiment_curriculumid;//
    //加入所有字段

    public static final String ID = "id";
    public static final String STUDENT_ID = "student_id";
    public static final String EXPERIMENT_ID = "experiment_id";
    public static final String CURRICULUM_ID = "curriculum_id";
    public static final String TRUENAME = "truename";
    public static final String SNO = "sno";
    public static final String SNO_EXP = "sno_exp";
    public static final String CLASSCODE = "classcode";
    public static final String SCORE = "score";
    public static final String STUDENT_GROUP_IS_ACTIVED = "student_group_is_actived";
    public static final String STUDENT_IS_ACTIVED = "student_is_actived";
    public static final String CURRICULUM_IS_ACTIVED = "curriculum_is_actived";
    public static final String EXPERIMENT_CURRICULUM_IS_ACTIVED = "experiment_curriculum_is_actived";
    public static final String SUBJECT_IS_ACTIVED = "subject_is_actived";
    public static final String STUDENT_GROUP_CODE = "student_group_code";
    public static final String STUDENT_GROUP_NAME = "student_group_name";
    public static final String COMMENT = "comment";
    public static final String MAINFLOW = "mainflow";
    public static final String REPORT = "report";
    public static final String RESULT = "result";
    public static final String SUBMIT = "submit";
    public static final String SCORESCRIPT = "scorescript";
    public static final String CREATE_GMT = "create_gmt";
    public static final String UPDATE_GMT = "update_gmt";
    public static final String WECHAT_OPENID = "wechat_openid";
    public static final String EXPERIMENT_TITLE = "experiment_title";
    public static final String EXPERIMENT_CONTENT = "experiment_content";
    public static final String EXPERIMENT_PURPOSES_REQUIREMENT = "experiment_purposes_requirement";
    public static final String SUBJECT_NAME = "subject_name";
    public static final String SUBJECT_ID = "subject_id";
    public static final String USER_ID = "user_id";
    public static final String CLOSING_GMT = "closing_gmt";
    public static final String OPENING_GMT = "opening_gmt";
    public static final String CURRICULUM_STUDENT_GROUPID = "curriculum_student_groupid";
    public static final String STUDENT_GROUP_ID = "student_group_id";
    public static final String REVIEWSTATE = "reviewstate";
    public static final String EXPERIMENT_CURRICULUMID = "experiment_curriculumid";

    public Vexperiment_record (Integer id, Integer student_id, Integer experiment_id, Integer curriculum_id, String truename, String sno, String sno_exp, String classcode, Integer score, Boolean student_group_is_actived, Boolean student_is_actived, Boolean curriculum_is_actived, Boolean experiment_curriculum_is_actived, Boolean subject_is_actived, String student_group_code, String student_group_name, String comment, String mainflow, String report, String result, Long submit, String scorescript, String wechat_openid, String experiment_title, String experiment_content, String experiment_purposes_requirement, String subject_name, Integer subject_id, Integer user_id, Long closing_gmt, Long opening_gmt, Integer curriculum_student_groupid, Integer student_group_id, Integer reviewstate, Integer experiment_curriculumid) {
        this.id = id;
        this.student_id = student_id;
        this.experiment_id = experiment_id;
        this.curriculum_id = curriculum_id;
        this.truename = truename;
        this.sno = sno;
        this.sno_exp = sno_exp;
        this.classcode = classcode;
        this.score = score;
        this.student_group_is_actived = student_group_is_actived;
        this.student_is_actived = student_is_actived;
        this.curriculum_is_actived = curriculum_is_actived;
        this.experiment_curriculum_is_actived = experiment_curriculum_is_actived;
        this.subject_is_actived = subject_is_actived;
        this.student_group_code = student_group_code;
        this.student_group_name = student_group_name;
        this.comment = comment;
        this.mainflow = mainflow;
        this.report = report;
        this.result = result;
        this.submit = submit;
        this.scorescript = scorescript;
        this.create_gmt = new  Date().getTime();
        this.update_gmt = 0l;
        this.wechat_openid = wechat_openid;
        this.experiment_title = experiment_title;
        this.experiment_content = experiment_content;
        this.experiment_purposes_requirement = experiment_purposes_requirement;
        this.subject_name = subject_name;
        this.subject_id = subject_id;
        this.user_id = user_id;
        this.closing_gmt = closing_gmt;
        this.opening_gmt = opening_gmt;
        this.curriculum_student_groupid = curriculum_student_groupid;
        this.student_group_id = student_group_id;
        this.reviewstate = reviewstate;
        this.experiment_curriculumid = experiment_curriculumid;
    }

    public Vexperiment_record (Integer student_id,Integer experiment_id,Integer curriculum_id,String truename,String sno,String sno_exp,String classcode,Integer score,Boolean student_group_is_actived,Boolean student_is_actived,Boolean curriculum_is_actived,Boolean experiment_curriculum_is_actived,Boolean subject_is_actived,String student_group_code,String student_group_name,String comment,String mainflow,String report,String result,Long submit,String scorescript,String wechat_openid,String experiment_title,String experiment_content,String experiment_purposes_requirement,String subject_name,Integer subject_id,Integer user_id,Long closing_gmt,Long opening_gmt,Integer curriculum_student_groupid,Integer student_group_id,Integer reviewstate,Integer experiment_curriculumid) {
        this.student_id = student_id;
        this.experiment_id = experiment_id;
        this.curriculum_id = curriculum_id;
        this.truename = truename;
        this.sno = sno;
        this.sno_exp = sno_exp;
        this.classcode = classcode;
        this.score = score;
        this.student_group_is_actived = student_group_is_actived;
        this.student_is_actived = student_is_actived;
        this.curriculum_is_actived = curriculum_is_actived;
        this.experiment_curriculum_is_actived = experiment_curriculum_is_actived;
        this.subject_is_actived = subject_is_actived;
        this.student_group_code = student_group_code;
        this.student_group_name = student_group_name;
        this.comment = comment;
        this.mainflow = mainflow;
        this.report = report;
        this.result = result;
        this.submit = submit;
        this.scorescript = scorescript;
        this.create_gmt = new  Date().getTime();
        this.update_gmt = 0l;
        this.wechat_openid = wechat_openid;
        this.experiment_title = experiment_title;
        this.experiment_content = experiment_content;
        this.experiment_purposes_requirement = experiment_purposes_requirement;
        this.subject_name = subject_name;
        this.subject_id = subject_id;
        this.user_id = user_id;
        this.closing_gmt = closing_gmt;
        this.opening_gmt = opening_gmt;
        this.curriculum_student_groupid = curriculum_student_groupid;
        this.student_group_id = student_group_id;
        this.reviewstate = reviewstate;
        this.experiment_curriculumid = experiment_curriculumid;
    }

    //加入公用属性
    /**
    * 实验提交时间
    */
    public Date getSubmit_date(){
        return new Date(submit); 
    }
    /**
    * 创建时间
    */
    public Date getCreate_gmt_date(){
        return new Date(create_gmt); 
    }
    /**
    * 修改时间
    */
    public Date getUpdate_gmt_date(){
        return new Date(update_gmt); 
    }
    /**
    * 
    */
    public Date getClosing_gmt_date(){
        return new Date(closing_gmt); 
    }
    /**
    * 
    */
    public Date getOpening_gmt_date(){
        return new Date(opening_gmt); 
    }
}
