<!------------------------------->
<!---- Generated By Denny(luhox@qq.com), cslite for sm -->
<!---- Remarks: ItemListHTML-->
<!---- Date Generated: 2020-10-09 10:48:00-->
<!------------------------------->
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<c:set var="searchpanel" value="true"></c:set>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<jsp:include page="../inc/bsa_head.jsp"></jsp:include>
<jsp:include page="../inc/ket.jsp"></jsp:include>
<link href="bssets/css/bsat1-white.css" rel="stylesheet" />
<title>${pagetitle}-${appName}</title>
</head>
<body>
	<div id="wrapper">
		<jsp:include page="../inc/bsa_navtop.jsp"></jsp:include>
		<!--/. NAV TOP  -->
		<jsp:include page="../inc/bsa_navside.jsp"></jsp:include>
		<!-- /. NAV SIDE  -->
		<div id="page-wrapper">
			<div class="header">
				<h3 class="page-header">
					${pagetitle} <small>${subtitle}</small>
				</h3>
			</div>
			<div id="page-inner">
				<!-- content start -->
				<c:choose>
					<c:when test="${operate == null}">

						<!-- div Tables -->
						<div class="panel panel-default">
							<!--  <div class="panel-heading">${tabletitle}</div> -->
							<div class="row margin-xs">
								<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
										<div>
				<button class="btn btn-success" type="button"
					data-toggle="collapse" data-target="#searchPanel"
					aria-expanded="false" aria-controls="searchPanel">
					筛选条件</button>
					<a href="${pagename}?operate=add" class="btn btn-primary">新增</a>
										</div>
								</div>
<c:if test="${searchpanel=='true'}">
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		<div class="row">
			<div class="col-sm-12">
				<div id="searchPanel"
					<c:if test="${kw != null  || student_id_map != null  || experiment_id_map != null  || curriculum_id_map != null  || subject_id_map != null  || user_id_map != null  || student_group_id_map != null }">class="collapse in form-inline" </c:if>
					<c:if test="${kw == null  && student_id_map == null  && experiment_id_map == null  && curriculum_id_map == null  && subject_id_map == null  && user_id_map == null  && student_group_id_map == null }">class="collapse form-inline" </c:if>>
					<div class="well">
						<!-- 面板 -->
						<div class="row">
							<div
								class="col-xs-4 col-sm-3 col-md-2 col-lg-2 text-right margin-top-xs">
								模糊查询：</div>
							<div class="col-xs-6 col-sm-4 col-md-4 col-lg-3">
								<div class="form-group">
									<input style="width: 100%;" type="text"
										class="form-control" id="kw" name="kw" value="${kw}"
										placeholder="模糊查询">
								</div>
							</div>
						</div>
						<div class="clearfix showborder-top"></div>
						<!-- 搜索条件： -->
						<div class="row">
							<div class="col-xs-4 col-sm-3 col-md-2 col-lg-2 text-right margin-top-xs">
								:</div>
							<c:forEach var="item" items="${studentlist}" varStatus="i">
<!-- checkbox begin -->
								<div class="col-xs-4 col-sm-3 col-md-3 col-lg-3">
									<div class="checkbox3 checkbox-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} checkbox-check checkbox-light">
										<input value="${item.id}" id="student_id${i.count}"
class="student_id_ck" type="checkbox"
<c:if test="${student_id_map.get(item.id) != null}">checked</c:if>>
										<label for="student_id${i.count}"> ${item.name} </label>
									</div>
								</div>
<!-- checkbox end -->
<!-- radio begin -->
			<div class="radio3 radio-check radio-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} radio-inline">
				<input type="radio" id="student_id${i.count}" name="student_id" value="${item.id}" <c:if test="${student_id_map.get(item.id) != null}">checked</c:if>> <label for="student_id${i.count}">${item.name}</label>
			</div>
<!-- radio end -->
								<div class="visible-lg-block">
									<c:if test="${i.count % 3==0}">
										<div class="clearfix"></div>
										<div class="col-lg-2"></div>
									</c:if>
								</div>
								<div class="visible-md-block">
									<c:if test="${i.count % 3==0}">
										<div class="clearfix"></div>
										<div class="col-md-2"></div>
									</c:if>
								</div>
								<div class="visible-sm-block">
									<c:if test="${i.count % 3==0}">
										<div class="clearfix"></div>
										<div class="col-sm-3"></div>
									</c:if>
								</div>
								<div class="visible-xs-block">
									<c:if test="${i.count % 2==0}">
										<div class="clearfix"></div>
										<div class="col-xs-4"></div>
									</c:if>
								</div>
							</c:forEach>
						</div>
						<div class="clearfix showborder-top"></div>
						<!-- /搜索条件： -->
						<!-- 搜索条件：实验id -->
						<div class="row">
							<div class="col-xs-4 col-sm-3 col-md-2 col-lg-2 text-right margin-top-xs">
								实验:</div>
							<c:forEach var="item" items="${experimentlist}" varStatus="i">
<!-- checkbox begin -->
								<div class="col-xs-4 col-sm-3 col-md-3 col-lg-3">
									<div class="checkbox3 checkbox-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} checkbox-check checkbox-light">
										<input value="${item.id}" id="experiment_id${i.count}"
class="experiment_id_ck" type="checkbox"
<c:if test="${experiment_id_map.get(item.id) != null}">checked</c:if>>
										<label for="experiment_id${i.count}"> ${item.name} </label>
									</div>
								</div>
<!-- checkbox end -->
<!-- radio begin -->
			<div class="radio3 radio-check radio-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} radio-inline">
				<input type="radio" id="experiment_id${i.count}" name="experiment_id" value="${item.id}" <c:if test="${experiment_id_map.get(item.id) != null}">checked</c:if>> <label for="experiment_id${i.count}">${item.name}</label>
			</div>
<!-- radio end -->
								<div class="visible-lg-block">
									<c:if test="${i.count % 3==0}">
										<div class="clearfix"></div>
										<div class="col-lg-2"></div>
									</c:if>
								</div>
								<div class="visible-md-block">
									<c:if test="${i.count % 3==0}">
										<div class="clearfix"></div>
										<div class="col-md-2"></div>
									</c:if>
								</div>
								<div class="visible-sm-block">
									<c:if test="${i.count % 3==0}">
										<div class="clearfix"></div>
										<div class="col-sm-3"></div>
									</c:if>
								</div>
								<div class="visible-xs-block">
									<c:if test="${i.count % 2==0}">
										<div class="clearfix"></div>
										<div class="col-xs-4"></div>
									</c:if>
								</div>
							</c:forEach>
						</div>
						<div class="clearfix showborder-top"></div>
						<!-- /搜索条件：实验id -->
						<!-- 搜索条件： -->
						<div class="row">
							<div class="col-xs-4 col-sm-3 col-md-2 col-lg-2 text-right margin-top-xs">
								:</div>
							<c:forEach var="item" items="${curriculumlist}" varStatus="i">
<!-- checkbox begin -->
								<div class="col-xs-4 col-sm-3 col-md-3 col-lg-3">
									<div class="checkbox3 checkbox-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} checkbox-check checkbox-light">
										<input value="${item.id}" id="curriculum_id${i.count}"
class="curriculum_id_ck" type="checkbox"
<c:if test="${curriculum_id_map.get(item.id) != null}">checked</c:if>>
										<label for="curriculum_id${i.count}"> ${item.name} </label>
									</div>
								</div>
<!-- checkbox end -->
<!-- radio begin -->
			<div class="radio3 radio-check radio-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} radio-inline">
				<input type="radio" id="curriculum_id${i.count}" name="curriculum_id" value="${item.id}" <c:if test="${curriculum_id_map.get(item.id) != null}">checked</c:if>> <label for="curriculum_id${i.count}">${item.name}</label>
			</div>
<!-- radio end -->
								<div class="visible-lg-block">
									<c:if test="${i.count % 3==0}">
										<div class="clearfix"></div>
										<div class="col-lg-2"></div>
									</c:if>
								</div>
								<div class="visible-md-block">
									<c:if test="${i.count % 3==0}">
										<div class="clearfix"></div>
										<div class="col-md-2"></div>
									</c:if>
								</div>
								<div class="visible-sm-block">
									<c:if test="${i.count % 3==0}">
										<div class="clearfix"></div>
										<div class="col-sm-3"></div>
									</c:if>
								</div>
								<div class="visible-xs-block">
									<c:if test="${i.count % 2==0}">
										<div class="clearfix"></div>
										<div class="col-xs-4"></div>
									</c:if>
								</div>
							</c:forEach>
						</div>
						<div class="clearfix showborder-top"></div>
						<!-- /搜索条件： -->
						<!-- 搜索条件：学科 -->
						<div class="row">
							<div class="col-xs-4 col-sm-3 col-md-2 col-lg-2 text-right margin-top-xs">
								学科:</div>
							<c:forEach var="item" items="${subjectlist}" varStatus="i">
<!-- checkbox begin -->
								<div class="col-xs-4 col-sm-3 col-md-3 col-lg-3">
									<div class="checkbox3 checkbox-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} checkbox-check checkbox-light">
										<input value="${item.id}" id="subject_id${i.count}"
class="subject_id_ck" type="checkbox"
<c:if test="${subject_id_map.get(item.id) != null}">checked</c:if>>
										<label for="subject_id${i.count}"> ${item.name} </label>
									</div>
								</div>
<!-- checkbox end -->
<!-- radio begin -->
			<div class="radio3 radio-check radio-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} radio-inline">
				<input type="radio" id="subject_id${i.count}" name="subject_id" value="${item.id}" <c:if test="${subject_id_map.get(item.id) != null}">checked</c:if>> <label for="subject_id${i.count}">${item.name}</label>
			</div>
<!-- radio end -->
								<div class="visible-lg-block">
									<c:if test="${i.count % 3==0}">
										<div class="clearfix"></div>
										<div class="col-lg-2"></div>
									</c:if>
								</div>
								<div class="visible-md-block">
									<c:if test="${i.count % 3==0}">
										<div class="clearfix"></div>
										<div class="col-md-2"></div>
									</c:if>
								</div>
								<div class="visible-sm-block">
									<c:if test="${i.count % 3==0}">
										<div class="clearfix"></div>
										<div class="col-sm-3"></div>
									</c:if>
								</div>
								<div class="visible-xs-block">
									<c:if test="${i.count % 2==0}">
										<div class="clearfix"></div>
										<div class="col-xs-4"></div>
									</c:if>
								</div>
							</c:forEach>
						</div>
						<div class="clearfix showborder-top"></div>
						<!-- /搜索条件：学科 -->
						<!-- 搜索条件：教师 -->
						<div class="row">
							<div class="col-xs-4 col-sm-3 col-md-2 col-lg-2 text-right margin-top-xs">
								教师:</div>
							<c:forEach var="item" items="${userlist}" varStatus="i">
<!-- checkbox begin -->
								<div class="col-xs-4 col-sm-3 col-md-3 col-lg-3">
									<div class="checkbox3 checkbox-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} checkbox-check checkbox-light">
										<input value="${item.id}" id="user_id${i.count}"
class="user_id_ck" type="checkbox"
<c:if test="${user_id_map.get(item.id) != null}">checked</c:if>>
										<label for="user_id${i.count}"> ${item.name} </label>
									</div>
								</div>
<!-- checkbox end -->
<!-- radio begin -->
			<div class="radio3 radio-check radio-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} radio-inline">
				<input type="radio" id="user_id${i.count}" name="user_id" value="${item.id}" <c:if test="${user_id_map.get(item.id) != null}">checked</c:if>> <label for="user_id${i.count}">${item.name}</label>
			</div>
<!-- radio end -->
								<div class="visible-lg-block">
									<c:if test="${i.count % 3==0}">
										<div class="clearfix"></div>
										<div class="col-lg-2"></div>
									</c:if>
								</div>
								<div class="visible-md-block">
									<c:if test="${i.count % 3==0}">
										<div class="clearfix"></div>
										<div class="col-md-2"></div>
									</c:if>
								</div>
								<div class="visible-sm-block">
									<c:if test="${i.count % 3==0}">
										<div class="clearfix"></div>
										<div class="col-sm-3"></div>
									</c:if>
								</div>
								<div class="visible-xs-block">
									<c:if test="${i.count % 2==0}">
										<div class="clearfix"></div>
										<div class="col-xs-4"></div>
									</c:if>
								</div>
							</c:forEach>
						</div>
						<div class="clearfix showborder-top"></div>
						<!-- /搜索条件：教师 -->
						<!-- 搜索条件：分组id -->
						<div class="row">
							<div class="col-xs-4 col-sm-3 col-md-2 col-lg-2 text-right margin-top-xs">
								分组:</div>
							<c:forEach var="item" items="${student_grouplist}" varStatus="i">
<!-- checkbox begin -->
								<div class="col-xs-4 col-sm-3 col-md-3 col-lg-3">
									<div class="checkbox3 checkbox-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} checkbox-check checkbox-light">
										<input value="${item.id}" id="student_group_id${i.count}"
class="student_group_id_ck" type="checkbox"
<c:if test="${student_group_id_map.get(item.id) != null}">checked</c:if>>
										<label for="student_group_id${i.count}"> ${item.name} </label>
									</div>
								</div>
<!-- checkbox end -->
<!-- radio begin -->
			<div class="radio3 radio-check radio-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} radio-inline">
				<input type="radio" id="student_group_id${i.count}" name="student_group_id" value="${item.id}" <c:if test="${student_group_id_map.get(item.id) != null}">checked</c:if>> <label for="student_group_id${i.count}">${item.name}</label>
			</div>
<!-- radio end -->
								<div class="visible-lg-block">
									<c:if test="${i.count % 3==0}">
										<div class="clearfix"></div>
										<div class="col-lg-2"></div>
									</c:if>
								</div>
								<div class="visible-md-block">
									<c:if test="${i.count % 3==0}">
										<div class="clearfix"></div>
										<div class="col-md-2"></div>
									</c:if>
								</div>
								<div class="visible-sm-block">
									<c:if test="${i.count % 3==0}">
										<div class="clearfix"></div>
										<div class="col-sm-3"></div>
									</c:if>
								</div>
								<div class="visible-xs-block">
									<c:if test="${i.count % 2==0}">
										<div class="clearfix"></div>
										<div class="col-xs-4"></div>
									</c:if>
								</div>
							</c:forEach>
						</div>
						<div class="clearfix showborder-top"></div>
						<!-- /搜索条件：分组id -->

						<div class="clearfix"></div>
						<div class="row">
							<div class="col-xs-12 col-sm-12 col-md-4 col-lg-3">
								<button id="searchbtn" class="btn btn-warning">搜索</button>
							</div>
							<div class="col-xs-12 col-sm-12 col-md-4 col-lg-3">
								<button class="btn btn-danger canclesearch">清除搜索条件</button>
							</div>
						</div>
						<!-- /面板 -->
					</div>

				</div>

			</div>
		</div>
	</div>
</c:if>
							</div>
							<jsp:include page="../inc/pager.jsp"></jsp:include>
<!-- div表格  (中大屏幕，表格显示) begin -->

						<!-- Advanced Tables -->
						<div class="panel panel-default  visible-md-block visible-lg-block">
							<!-- <div class="panel-heading">${tabletitle}</div> -->
							<div class="row">
								<div class="col-md-12">
									<div class="panel-body">
										<div class="table-responsive">
											<table class="table table-striped table-bordered table-hover"
												id="dataTables-example">
												<thead>
													<tr class="bg-blue">
														<th>序号</th>
														<th></th>
														<th></th>
														<th>实验id</th>
														<th></th>
														<th>用户名称</th>
														<th>学号</th>
														<th>学号</th>
														<th>学校的班级号，不是系统内的班级号</th>
														<th>实验成绩</th>
														<th>是否可以登录</th>
														<th>冻结账号</th>
														<th></th>
														<th></th>
														<th>是否显示</th>
														<th>分组编号，8位字符</th>
														<th>组名</th>
														<th>对实验报告的评语，100字以内！</th>
														<th>实验主要流程、基本操作或核心代码、算法片段</th>
														<th>实验报告，用xml记录实验结果</th>
														<th>实验结果的分析与评价</th>
														<th>实验提交时间</th>
														<th>成绩描述：优秀/良好/中等/及格/不及格</th>
														<th>创建时间</th>
														<th>修改时间</th>
														<th>微信openid</th>
														<th>实验标题</th>
														<th>实验内容</th>
														<th>实验目的及要求</th>
														<th>科目标题</th>
														<th>学科</th>
														<th>教师</th>
														<th></th>
														<th></th>
														<th>班级</th>
														<th>分组id</th>
														<th>评阅状态1已评,2待评</th>
														<th></th>
														<th>操作</th>
													</tr>
												</thead>
												<tbody>
													<c:forEach var="it" items="${list}" varStatus="index">
														<tr>
															<td id="t${it.id}">${index.count+(pager.current - 1) * pager.size}</td>
															<td>${it.id}</td>
															<td>${studentmap[it.student_id]}</td>
															<td>${experimentmap[it.experiment_id]}</td>
															<td>${curriculummap[it.curriculum_id]}</td>
															<td>${it.truename}</td>
															<td>${it.sno}</td>
															<td>${it.sno_exp}</td>
															<td>${it.classcode}</td>
															<td>${it.score}</td>
															<td>
	<c:choose>
		<c:when test="${it.student_group_is_actived}">
			<a href="${basePath}${pagename}?operate=hideitem&id=${it.id}" ><img alt="" src="bssets/i/greendot.png"></a>
		</c:when>
		<c:when test="${it.student_group_is_actived==false}">
			<a href="${basePath}${pagename}?operate=showitem&id=${it.id}" ><img alt="" src="bssets/i/reddot.png"></a>
		</c:when>
	</c:choose>
</td>
															<td>
	<c:choose>
		<c:when test="${it.student_is_actived}">
			<a href="${basePath}${pagename}?operate=hideitem&id=${it.id}" ><img alt="" src="bssets/i/greendot.png"></a>
		</c:when>
		<c:when test="${it.student_is_actived==false}">
			<a href="${basePath}${pagename}?operate=showitem&id=${it.id}" ><img alt="" src="bssets/i/reddot.png"></a>
		</c:when>
	</c:choose>
</td>
															<td>
	<c:choose>
		<c:when test="${it.curriculum_is_actived}">
			<a href="${basePath}${pagename}?operate=hideitem&id=${it.id}" ><img alt="" src="bssets/i/greendot.png"></a>
		</c:when>
		<c:when test="${it.curriculum_is_actived==false}">
			<a href="${basePath}${pagename}?operate=showitem&id=${it.id}" ><img alt="" src="bssets/i/reddot.png"></a>
		</c:when>
	</c:choose>
</td>
															<td>
	<c:choose>
		<c:when test="${it.experiment_curriculum_is_actived}">
			<a href="${basePath}${pagename}?operate=hideitem&id=${it.id}" ><img alt="" src="bssets/i/greendot.png"></a>
		</c:when>
		<c:when test="${it.experiment_curriculum_is_actived==false}">
			<a href="${basePath}${pagename}?operate=showitem&id=${it.id}" ><img alt="" src="bssets/i/reddot.png"></a>
		</c:when>
	</c:choose>
</td>
															<td>
	<c:choose>
		<c:when test="${it.subject_is_actived}">
			<a href="${basePath}${pagename}?operate=hideitem&id=${it.id}" ><img alt="" src="bssets/i/greendot.png"></a>
		</c:when>
		<c:when test="${it.subject_is_actived==false}">
			<a href="${basePath}${pagename}?operate=showitem&id=${it.id}" ><img alt="" src="bssets/i/reddot.png"></a>
		</c:when>
	</c:choose>
</td>
															<td>${it.student_group_code}</td>
															<td>${it.student_group_name}</td>
															<td>${it.comment}</td>
															<td>${it.mainflow}</td>
															<td>${it.report}</td>
															<td>${it.result}</td>
															<td><c:if test="${it.submit !=0}"><fmt:formatDate pattern="yyyy-MM-dd" value="${it.submit_date}" /></c:if></td>
															<td>${it.scorescript}</td>
															<td><c:if test="${it.create_gmt !=0}"><fmt:formatDate pattern="yyyy-MM-dd" value="${it.create_gmt_date}" /></c:if></td>
															<td><c:if test="${it.update_gmt !=0}"><fmt:formatDate pattern="yyyy-MM-dd" value="${it.update_gmt_date}" /></c:if></td>
															<td>${it.wechat_openid}</td>
															<td>${it.experiment_title}</td>
															<td>${it.experiment_content}</td>
															<td>${it.experiment_purposes_requirement}</td>
															<td>${it.subject_name}</td>
															<td>${subjectmap[it.subject_id]}</td>
															<td>${usermap[it.user_id]}</td>
															<td><c:if test="${it.closing_gmt !=0}"><fmt:formatDate pattern="yyyy-MM-dd" value="${it.closing_gmt_date}" /></c:if></td>
															<td><c:if test="${it.opening_gmt !=0}"><fmt:formatDate pattern="yyyy-MM-dd" value="${it.opening_gmt_date}" /></c:if></td>
															<td>${it.curriculum_student_groupid}</td>
															<td>${student_groupmap[it.student_group_id]}</td>
															<td>${it.reviewstate}</td>
															<td>${it.experiment_curriculumid}</td>
															<td>
<a href="${basePath}${pagename}?operate=moveup&id=${it.id}" class="btn btn-sm btn-info" <c:if test="${index.count==1}">disabled</c:if>>上移</a>
<a href="${basePath}${pagename}?operate=movedown&id=${it.id}" class="btn btn-sm btn-warning" <c:if test="${index.count==pager.total}">disabled</c:if>>下移</a>
<a href="${basePath}${pagename}?operate=edit&id=${it.id}" class="btn btn-sm btn-success">编辑</a>
<button value="${it.id}" class="deleteitem btn btn-sm btn-danger">删除</button>
															</td>
														</tr>
													</c:forEach>
												</tbody>
											</table>
										</div>
									</div>
								</div>
							</div>
						</div>
						<!--End Advanced Tables -->
<!-- div表格  (中大屏幕，表格显示) end -->
<!-- div表格  (小屏幕，类卡片显示) begin -->
<div class="panel-body visible-xs-block visible-sm-block">
<div class="row">
	<c:forEach var="it" items="${list}" varStatus="index">
		<div class="col-xs-12 col-sm-6">
			<div class="row showbd margin-xs borderradius05">
				<div class="col-xs-12 col-sm-12 bg-primary padding-xs borderradius05" id="t${it.id}"><h3>${index.count+(pager.current - 1) * pager.size}</h3></div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.id}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.student_id}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.experiment_id}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.curriculum_id}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.truename}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.sno}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.sno_exp}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.classcode}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.score}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.student_group_is_actived}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.student_is_actived}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.curriculum_is_actived}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.experiment_curriculum_is_actived}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.subject_is_actived}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.student_group_code}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.student_group_name}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.comment}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.mainflow}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.report}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.result}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12"><c:if test="${it.submit !=0}"><fmt:formatDate pattern="yyyy-MM-dd" value="${it.submit_date}" /></c:if></div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.scorescript}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12"><c:if test="${it.create_gmt !=0}"><fmt:formatDate pattern="yyyy-MM-dd" value="${it.create_gmt_date}" /></c:if></div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12"><c:if test="${it.update_gmt !=0}"><fmt:formatDate pattern="yyyy-MM-dd" value="${it.update_gmt_date}" /></c:if></div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.wechat_openid}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.experiment_title}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.experiment_content}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.experiment_purposes_requirement}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.subject_name}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.subject_id}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.user_id}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12"><c:if test="${it.closing_gmt !=0}"><fmt:formatDate pattern="yyyy-MM-dd" value="${it.closing_gmt_date}" /></c:if></div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12"><c:if test="${it.opening_gmt !=0}"><fmt:formatDate pattern="yyyy-MM-dd" value="${it.opening_gmt_date}" /></c:if></div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.curriculum_student_groupid}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.student_group_id}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.reviewstate}</div>
				<div class="clearfix"></div>

			<div class="col-xs-12 col-sm-12">${it.experiment_curriculumid}</div>
				<div class="clearfix"></div>

				<div class="col-xs-12 col-sm-12">
<a href="${basePath}${pagename}?operate=moveup&id=${it.id}" class="btn btn-sm btn-info" <c:if test="${index.count==1}">disabled</c:if>>上移</a>
<a href="${basePath}${pagename}?operate=movedown&id=${it.id}" class="btn btn-sm btn-warning" <c:if test="${index.count==pager.total}">disabled</c:if>>下移</a>
<a href="${basePath}${pagename}?operate=edit&id=${it.id}" class="btn btn-sm btn-success">编辑</a>
<button value="${it.id}" class="deleteitem btn btn-sm btn-danger">删除</button>
				</div>
			</div>
		</div>
	</c:forEach>
</div>
</div>
<!-- div表格  (小屏幕，类卡片显示) end -->
						</div>
						<!--End div Tables -->
					</c:when>
					<c:when test="${operate == 'add'}">
						<div class="row">
							<div class="col-xs-12">
								<div class="panel panel-default">
									<div class="panel-heading">
										<div class="card-title">
<div class="title">${formtitle}</div>
										</div>
									</div>
									<div class="panel-body">
<a class="btn btn-warning" href="${pagename}">放弃保存，直接返回</a>
										<form id="form1" class="form-horizontal" method="post"
action="${pagename}">
<input type="hidden" name="operate" value="addform" /> 
<input type="hidden" name="referer" value="${referer}" />
<!-- selectbox begin -->
<div class="form-group">
	<label for="student_id" class="col-sm-3 control-label"></label>
	<div class="col-sm-9">
		<select class="selectbox" id="student_id" name="student_id"  style="width:100%;">
			<c:forEach var="item" items="${studentlist}" varStatus="i">
				<option value="${item.id}" >${item.name}</option>
			</c:forEach>
		</select>
	</div>
</div>
<!-- selectbox end -->
<!-- radio begin -->
			<c:forEach var="item" items="${studentlist}" varStatus="i">
			<div class="radio3 radio-check radio-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} radio-inline">
				<input type="radio" id="student_id${i.count}" name="student_id" value="${item.id}" <c:if test="${i.count==1}">checked</c:if>> <label for="student_id${i.count}">${item.name}</label>
			</div>
			</c:forEach>
<!-- radio end -->
<!-- selectbox begin -->
<div class="form-group">
	<label for="experiment_id" class="col-sm-3 control-label">实验id</label>
	<div class="col-sm-9">
		<select class="selectbox" id="experiment_id" name="experiment_id"  style="width:100%;">
			<c:forEach var="item" items="${experimentlist}" varStatus="i">
				<option value="${item.id}" >${item.name}</option>
			</c:forEach>
		</select>
	</div>
</div>
<!-- selectbox end -->
<!-- radio begin -->
			<c:forEach var="item" items="${experimentlist}" varStatus="i">
			<div class="radio3 radio-check radio-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} radio-inline">
				<input type="radio" id="experiment_id${i.count}" name="experiment_id" value="${item.id}" <c:if test="${i.count==1}">checked</c:if>> <label for="experiment_id${i.count}">${item.name}</label>
			</div>
			</c:forEach>
<!-- radio end -->
<!-- selectbox begin -->
<div class="form-group">
	<label for="curriculum_id" class="col-sm-3 control-label"></label>
	<div class="col-sm-9">
		<select class="selectbox" id="curriculum_id" name="curriculum_id"  style="width:100%;">
			<c:forEach var="item" items="${curriculumlist}" varStatus="i">
				<option value="${item.id}" >${item.name}</option>
			</c:forEach>
		</select>
	</div>
</div>
<!-- selectbox end -->
<!-- radio begin -->
			<c:forEach var="item" items="${curriculumlist}" varStatus="i">
			<div class="radio3 radio-check radio-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} radio-inline">
				<input type="radio" id="curriculum_id${i.count}" name="curriculum_id" value="${item.id}" <c:if test="${i.count==1}">checked</c:if>> <label for="curriculum_id${i.count}">${item.name}</label>
			</div>
			</c:forEach>
<!-- radio end -->
<div class="form-group">
	<label for="truename" class="col-sm-3 control-label">用户名称</label>
	<div class="col-sm-9">
		<input type="text" class="form-control" id="truename"
			name="truename" placeholder="用户名称">
	</div>
</div>
<div class="form-group">
	<label for="sno" class="col-sm-3 control-label">学号</label>
	<div class="col-sm-9">
		<input type="text" class="form-control" id="sno"
			name="sno" placeholder="学号">
	</div>
</div>
<div class="form-group">
	<label for="sno_exp" class="col-sm-3 control-label">学号</label>
	<div class="col-sm-9">
		<input type="text" class="form-control" id="sno_exp"
			name="sno_exp" placeholder="学号">
	</div>
</div>
<div class="form-group">
	<label for="classcode" class="col-sm-3 control-label">学校的班级号，不是系统内的班级号</label>
	<div class="col-sm-9">
		<input type="text" class="form-control" id="classcode"
			name="classcode" placeholder="学校的班级号，不是系统内的班级号">
	</div>
</div>
<div class="form-group">
	<label for="score" class="col-sm-3 control-label">实验成绩</label>
	<div class="col-sm-9">
		<input type="text" class="form-control restrictnumber" id="score"
			name="score" placeholder="实验成绩" >
	</div>
</div>
<div class="form-group">
	<label for="student_group_is_actived" class="col-sm-3 control-label">是否可以登录</label>
	<div class="col-sm-9">
		<div
			class="checkbox3 checkbox-round checkbox-check checkbox-light">
					<input type="checkbox" id="student_group_is_actived" name="student_group_is_actived">
			<label for="student_group_is_actived"> 是否可以登录 </label>
		</div>
	</div>
</div>
<div class="form-group">
	<label for="student_is_actived" class="col-sm-3 control-label">冻结账号</label>
	<div class="col-sm-9">
		<div
			class="checkbox3 checkbox-round checkbox-check checkbox-light">
					<input type="checkbox" id="student_is_actived" name="student_is_actived">
			<label for="student_is_actived"> 冻结账号 </label>
		</div>
	</div>
</div>
<div class="form-group">
	<label for="curriculum_is_actived" class="col-sm-3 control-label"></label>
	<div class="col-sm-9">
		<div
			class="checkbox3 checkbox-round checkbox-check checkbox-light">
					<input type="checkbox" id="curriculum_is_actived" name="curriculum_is_actived">
			<label for="curriculum_is_actived">  </label>
		</div>
	</div>
</div>
<div class="form-group">
	<label for="experiment_curriculum_is_actived" class="col-sm-3 control-label"></label>
	<div class="col-sm-9">
		<div
			class="checkbox3 checkbox-round checkbox-check checkbox-light">
					<input type="checkbox" id="experiment_curriculum_is_actived" name="experiment_curriculum_is_actived">
			<label for="experiment_curriculum_is_actived">  </label>
		</div>
	</div>
</div>
<div class="form-group">
	<label for="subject_is_actived" class="col-sm-3 control-label">是否显示</label>
	<div class="col-sm-9">
		<div
			class="checkbox3 checkbox-round checkbox-check checkbox-light">
					<input type="checkbox" id="subject_is_actived" name="subject_is_actived">
			<label for="subject_is_actived"> 是否显示 </label>
		</div>
	</div>
</div>
<div class="form-group">
	<label for="student_group_code" class="col-sm-3 control-label">分组编号，8位字符</label>
	<div class="col-sm-9">
		<input type="text" class="form-control" id="student_group_code"
			name="student_group_code" placeholder="分组编号，8位字符">
	</div>
</div>
<div class="form-group">
	<label for="student_group_name" class="col-sm-3 control-label">组名</label>
	<div class="col-sm-9">
		<input type="text" class="form-control" id="student_group_name"
			name="student_group_name" placeholder="组名">
	</div>
</div>
<div class="form-group">
	<label for="comment" class="col-sm-3 control-label">对实验报告的评语，100字以内！</label>
	<div class="col-sm-9">
		<input type="text" class="form-control" id="comment"
			name="comment" placeholder="对实验报告的评语，100字以内！">
	</div>
</div>
<div class="form-group">
	<label for="mainflow" class="col-sm-3 control-label">实验主要流程、基本操作或核心代码、算法片段</label>
	<div class="col-sm-9">
<textarea class="form-control" id="mainflow" name="mainflow" style="width:100%;height:400px;visibility:hidden;"></textarea>
	</div>
</div>
<div class="form-group">
	<label for="report" class="col-sm-3 control-label">实验报告，用xml记录实验结果</label>
	<div class="col-sm-9">
<textarea class="form-control" id="report" name="report" style="width:100%;height:400px;visibility:hidden;"></textarea>
	</div>
</div>
<div class="form-group">
	<label for="result" class="col-sm-3 control-label">实验结果的分析与评价</label>
	<div class="col-sm-9">
<textarea class="form-control" id="result" name="result" style="width:100%;height:400px;visibility:hidden;"></textarea>
	</div>
</div>
<div class="form-group d_t_dater">
	<label for="submit_date" class="col-sm-3 control-label">实验提交时间</label>
	<div class="col-sm-9">
		<div class="input-group">
	<span class="input-group-addon" style="cursor: pointer;"
	onclick="$.jeDate('#submit_date',{trigger:false,format: 'YYYY-MM-DD hh:mm:ss'})">实验提交时间</span>
<input placeholder="实验提交时间" type="text"
	class="form-control" id="submit_date"
	name="submit_date" readonly>
		</div>
	</div>
</div>
<div class="form-group">
	<label for="scorescript" class="col-sm-3 control-label">成绩描述：优秀/良好/中等/及格/不及格</label>
	<div class="col-sm-9">
		<input type="text" class="form-control" id="scorescript"
			name="scorescript" placeholder="成绩描述：优秀/良好/中等/及格/不及格">
	</div>
</div>
<div class="form-group d_t_dater">
	<label for="create_gmt_date" class="col-sm-3 control-label">创建时间</label>
	<div class="col-sm-9">
		<div class="input-group">
	<span class="input-group-addon" style="cursor: pointer;"
	onclick="$.jeDate('#create_gmt_date',{trigger:false,format: 'YYYY-MM-DD hh:mm:ss'})">创建时间</span>
<input placeholder="创建时间" type="text"
	class="form-control" id="create_gmt_date"
	name="create_gmt_date" readonly>
		</div>
	</div>
</div>
<div class="form-group d_t_dater">
	<label for="update_gmt_date" class="col-sm-3 control-label">修改时间</label>
	<div class="col-sm-9">
		<div class="input-group">
	<span class="input-group-addon" style="cursor: pointer;"
	onclick="$.jeDate('#update_gmt_date',{trigger:false,format: 'YYYY-MM-DD hh:mm:ss'})">修改时间</span>
<input placeholder="修改时间" type="text"
	class="form-control" id="update_gmt_date"
	name="update_gmt_date" readonly>
		</div>
	</div>
</div>
<div class="form-group">
	<label for="wechat_openid" class="col-sm-3 control-label">微信openid</label>
	<div class="col-sm-9">
		<input type="text" class="form-control" id="wechat_openid"
			name="wechat_openid" placeholder="微信openid">
	</div>
</div>
<div class="form-group">
	<label for="experiment_title" class="col-sm-3 control-label">实验标题</label>
	<div class="col-sm-9">
		<input type="text" class="form-control" id="experiment_title"
			name="experiment_title" placeholder="实验标题">
	</div>
</div>
<div class="form-group">
	<label for="experiment_content" class="col-sm-3 control-label">实验内容</label>
	<div class="col-sm-9">
<textarea class="form-control" id="experiment_content" name="experiment_content" style="width:100%;height:400px;visibility:hidden;"></textarea>
	</div>
</div>
<div class="form-group">
	<label for="experiment_purposes_requirement" class="col-sm-3 control-label">实验目的及要求</label>
	<div class="col-sm-9">
<textarea class="form-control" id="experiment_purposes_requirement" name="experiment_purposes_requirement" style="width:100%;height:400px;visibility:hidden;"></textarea>
	</div>
</div>
<div class="form-group">
	<label for="subject_name" class="col-sm-3 control-label">科目标题</label>
	<div class="col-sm-9">
		<input type="text" class="form-control" id="subject_name"
			name="subject_name" placeholder="科目标题">
	</div>
</div>
<!-- selectbox begin -->
<div class="form-group">
	<label for="subject_id" class="col-sm-3 control-label">学科</label>
	<div class="col-sm-9">
		<select class="selectbox" id="subject_id" name="subject_id"  style="width:100%;">
			<c:forEach var="item" items="${subjectlist}" varStatus="i">
				<option value="${item.id}" >${item.name}</option>
			</c:forEach>
		</select>
	</div>
</div>
<!-- selectbox end -->
<!-- radio begin -->
			<c:forEach var="item" items="${subjectlist}" varStatus="i">
			<div class="radio3 radio-check radio-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} radio-inline">
				<input type="radio" id="subject_id${i.count}" name="subject_id" value="${item.id}" <c:if test="${i.count==1}">checked</c:if>> <label for="subject_id${i.count}">${item.name}</label>
			</div>
			</c:forEach>
<!-- radio end -->
<!-- selectbox begin -->
<div class="form-group">
	<label for="user_id" class="col-sm-3 control-label">教师</label>
	<div class="col-sm-9">
		<select class="selectbox" id="user_id" name="user_id"  style="width:100%;">
			<c:forEach var="item" items="${userlist}" varStatus="i">
				<option value="${item.id}" >${item.name}</option>
			</c:forEach>
		</select>
	</div>
</div>
<!-- selectbox end -->
<!-- radio begin -->
			<c:forEach var="item" items="${userlist}" varStatus="i">
			<div class="radio3 radio-check radio-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} radio-inline">
				<input type="radio" id="user_id${i.count}" name="user_id" value="${item.id}" <c:if test="${i.count==1}">checked</c:if>> <label for="user_id${i.count}">${item.name}</label>
			</div>
			</c:forEach>
<!-- radio end -->
<div class="form-group d_t_dater">
	<label for="closing_gmt_date" class="col-sm-3 control-label"></label>
	<div class="col-sm-9">
		<div class="input-group">
	<span class="input-group-addon" style="cursor: pointer;"
	onclick="$.jeDate('#closing_gmt_date',{trigger:false,format: 'YYYY-MM-DD hh:mm:ss'})"></span>
<input placeholder="" type="text"
	class="form-control" id="closing_gmt_date"
	name="closing_gmt_date" readonly>
		</div>
	</div>
</div>
<div class="form-group d_t_dater">
	<label for="opening_gmt_date" class="col-sm-3 control-label"></label>
	<div class="col-sm-9">
		<div class="input-group">
	<span class="input-group-addon" style="cursor: pointer;"
	onclick="$.jeDate('#opening_gmt_date',{trigger:false,format: 'YYYY-MM-DD hh:mm:ss'})"></span>
<input placeholder="" type="text"
	class="form-control" id="opening_gmt_date"
	name="opening_gmt_date" readonly>
		</div>
	</div>
</div>
<div class="form-group">
	<label for="curriculum_student_groupid" class="col-sm-3 control-label">班级</label>
	<div class="col-sm-9">
		<input type="text" class="form-control restrictnumber" id="curriculum_student_groupid"
			name="curriculum_student_groupid" placeholder="班级" >
	</div>
</div>
<!-- selectbox begin -->
<div class="form-group">
	<label for="student_group_id" class="col-sm-3 control-label">分组id</label>
	<div class="col-sm-9">
		<select class="selectbox" id="student_group_id" name="student_group_id"  style="width:100%;">
			<c:forEach var="item" items="${student_grouplist}" varStatus="i">
				<option value="${item.id}" >${item.name}</option>
			</c:forEach>
		</select>
	</div>
</div>
<!-- selectbox end -->
<!-- radio begin -->
			<c:forEach var="item" items="${student_grouplist}" varStatus="i">
			<div class="radio3 radio-check radio-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} radio-inline">
				<input type="radio" id="student_group_id${i.count}" name="student_group_id" value="${item.id}" <c:if test="${i.count==1}">checked</c:if>> <label for="student_group_id${i.count}">${item.name}</label>
			</div>
			</c:forEach>
<!-- radio end -->
<div class="form-group">
	<label for="reviewstate" class="col-sm-3 control-label">评阅状态1已评,2待评</label>
	<div class="col-sm-9">
		<input type="text" class="form-control restrictnumber" id="reviewstate"
			name="reviewstate" placeholder="评阅状态1已评,2待评" >
	</div>
</div>
<div class="form-group">
	<label for="experiment_curriculumid" class="col-sm-3 control-label"></label>
	<div class="col-sm-9">
		<input type="text" class="form-control restrictnumber" id="experiment_curriculumid"
			name="experiment_curriculumid" placeholder="" >
	</div>
</div>
<div class="form-group">
	<div class="col-sm-offset-3 col-sm-9">
		<button type="submit" class="btn btn-success">添加信息</button>
	</div>
</div>
										</form>
									</div>
								</div>
							</div>
						</div>
					</c:when>
					<c:when test="${operate == 'edit'}">
						<div class="row">
							<div class="col-xs-12">
								<div class="panel panel-default">
									<div class="panel-heading">
										<div class="card-title">
<div class="title">${formtitle}</div>
										</div>
									</div>
									<div class="panel-body">
<a class="btn btn-warning" href="${pagename}">放弃保存，直接返回</a>
										<form id="form1" class="form-horizontal" method="post"
action="${pagename}">
<input type="hidden" name="operate" value="editform" /> <input
	type="hidden" name="id" value="${it.id}" />
<input type="hidden" name="referer" value="${referer}" />
<div class="form-group">
	<label for="id" class="col-sm-3 control-label"></label>
	<div class="col-sm-9">
		<input type="text" class="form-control restrictnumber" id="id"
			name="id" placeholder="" value="${it.id}">
	</div>
</div>
<!-- selectbox begin -->
<div class="form-group">
	<label for="student_id" class="col-sm-3 control-label"></label>
	<div class="col-sm-9">
		<select class="selectbox" id="student_id" name="student_id"  style="width:100%;">
			<c:forEach var="item" items="${studentlist}" varStatus="i">
				<option value="${item.id}"
					<c:if test="${item.id==it.student_id}">selected</c:if>>${item.name}</option>
			</c:forEach>
		</select>
	</div>
</div>
<!-- selectbox end -->
<!-- radio begin -->
			<c:forEach var="item" items="${studentlist}" varStatus="i">
			<div class="radio3 radio-check radio-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} radio-inline">
				<input type="radio" id="student_id${i.count}" name="student_id" value="${item.id}" <c:if test="${item.id==it.student_id}">checked</c:if>> <label for="student_id${i.count}">${item.name}</label>
			</div>
			</c:forEach>
<!-- radio end -->
<!-- selectbox begin -->
<div class="form-group">
	<label for="experiment_id" class="col-sm-3 control-label">实验id</label>
	<div class="col-sm-9">
		<select class="selectbox" id="experiment_id" name="experiment_id"  style="width:100%;">
			<c:forEach var="item" items="${experimentlist}" varStatus="i">
				<option value="${item.id}"
					<c:if test="${item.id==it.experiment_id}">selected</c:if>>${item.name}</option>
			</c:forEach>
		</select>
	</div>
</div>
<!-- selectbox end -->
<!-- radio begin -->
			<c:forEach var="item" items="${experimentlist}" varStatus="i">
			<div class="radio3 radio-check radio-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} radio-inline">
				<input type="radio" id="experiment_id${i.count}" name="experiment_id" value="${item.id}" <c:if test="${item.id==it.experiment_id}">checked</c:if>> <label for="experiment_id${i.count}">${item.name}</label>
			</div>
			</c:forEach>
<!-- radio end -->
<!-- selectbox begin -->
<div class="form-group">
	<label for="curriculum_id" class="col-sm-3 control-label"></label>
	<div class="col-sm-9">
		<select class="selectbox" id="curriculum_id" name="curriculum_id"  style="width:100%;">
			<c:forEach var="item" items="${curriculumlist}" varStatus="i">
				<option value="${item.id}"
					<c:if test="${item.id==it.curriculum_id}">selected</c:if>>${item.name}</option>
			</c:forEach>
		</select>
	</div>
</div>
<!-- selectbox end -->
<!-- radio begin -->
			<c:forEach var="item" items="${curriculumlist}" varStatus="i">
			<div class="radio3 radio-check radio-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} radio-inline">
				<input type="radio" id="curriculum_id${i.count}" name="curriculum_id" value="${item.id}" <c:if test="${item.id==it.curriculum_id}">checked</c:if>> <label for="curriculum_id${i.count}">${item.name}</label>
			</div>
			</c:forEach>
<!-- radio end -->
<div class="form-group">
	<label for="truename" class="col-sm-3 control-label">用户名称</label>
	<div class="col-sm-9">
		<input type="text" class="form-control" id="truename"
			name="truename" placeholder="用户名称" value="${it.truename}">
	</div>
</div>
<div class="form-group">
	<label for="sno" class="col-sm-3 control-label">学号</label>
	<div class="col-sm-9">
		<input type="text" class="form-control" id="sno"
			name="sno" placeholder="学号" value="${it.sno}">
	</div>
</div>
<div class="form-group">
	<label for="sno_exp" class="col-sm-3 control-label">学号</label>
	<div class="col-sm-9">
		<input type="text" class="form-control" id="sno_exp"
			name="sno_exp" placeholder="学号" value="${it.sno_exp}">
	</div>
</div>
<div class="form-group">
	<label for="classcode" class="col-sm-3 control-label">学校的班级号，不是系统内的班级号</label>
	<div class="col-sm-9">
		<input type="text" class="form-control" id="classcode"
			name="classcode" placeholder="学校的班级号，不是系统内的班级号" value="${it.classcode}">
	</div>
</div>
<div class="form-group">
	<label for="score" class="col-sm-3 control-label">实验成绩</label>
	<div class="col-sm-9">
		<input type="text" class="form-control restrictnumber" id="score"
			name="score" placeholder="实验成绩" value="${it.score}">
	</div>
</div>
<div class="form-group">
	<label for="student_group_is_actived" class="col-sm-3 control-label">是否可以登录</label>
	<div class="col-sm-9">
		<div
			class="checkbox3 checkbox-round checkbox-check checkbox-light">
			<c:choose>
				<c:when test="${it.student_group_is_actived == true}">
					<input type="checkbox" id="student_group_is_actived" name="student_group_is_actived"
						checked>
				</c:when>
				<c:when test="${it.student_group_is_actived == false}">
					<input type="checkbox" id="student_group_is_actived" name="student_group_is_actived">
				</c:when>
			</c:choose>
			<label for="student_group_is_actived"> 是否可以登录 </label>
		</div>
	</div>
</div>
<div class="form-group">
	<label for="student_is_actived" class="col-sm-3 control-label">冻结账号</label>
	<div class="col-sm-9">
		<div
			class="checkbox3 checkbox-round checkbox-check checkbox-light">
			<c:choose>
				<c:when test="${it.student_is_actived == true}">
					<input type="checkbox" id="student_is_actived" name="student_is_actived"
						checked>
				</c:when>
				<c:when test="${it.student_is_actived == false}">
					<input type="checkbox" id="student_is_actived" name="student_is_actived">
				</c:when>
			</c:choose>
			<label for="student_is_actived"> 冻结账号 </label>
		</div>
	</div>
</div>
<div class="form-group">
	<label for="curriculum_is_actived" class="col-sm-3 control-label"></label>
	<div class="col-sm-9">
		<div
			class="checkbox3 checkbox-round checkbox-check checkbox-light">
			<c:choose>
				<c:when test="${it.curriculum_is_actived == true}">
					<input type="checkbox" id="curriculum_is_actived" name="curriculum_is_actived"
						checked>
				</c:when>
				<c:when test="${it.curriculum_is_actived == false}">
					<input type="checkbox" id="curriculum_is_actived" name="curriculum_is_actived">
				</c:when>
			</c:choose>
			<label for="curriculum_is_actived">  </label>
		</div>
	</div>
</div>
<div class="form-group">
	<label for="experiment_curriculum_is_actived" class="col-sm-3 control-label"></label>
	<div class="col-sm-9">
		<div
			class="checkbox3 checkbox-round checkbox-check checkbox-light">
			<c:choose>
				<c:when test="${it.experiment_curriculum_is_actived == true}">
					<input type="checkbox" id="experiment_curriculum_is_actived" name="experiment_curriculum_is_actived"
						checked>
				</c:when>
				<c:when test="${it.experiment_curriculum_is_actived == false}">
					<input type="checkbox" id="experiment_curriculum_is_actived" name="experiment_curriculum_is_actived">
				</c:when>
			</c:choose>
			<label for="experiment_curriculum_is_actived">  </label>
		</div>
	</div>
</div>
<div class="form-group">
	<label for="subject_is_actived" class="col-sm-3 control-label">是否显示</label>
	<div class="col-sm-9">
		<div
			class="checkbox3 checkbox-round checkbox-check checkbox-light">
			<c:choose>
				<c:when test="${it.subject_is_actived == true}">
					<input type="checkbox" id="subject_is_actived" name="subject_is_actived"
						checked>
				</c:when>
				<c:when test="${it.subject_is_actived == false}">
					<input type="checkbox" id="subject_is_actived" name="subject_is_actived">
				</c:when>
			</c:choose>
			<label for="subject_is_actived"> 是否显示 </label>
		</div>
	</div>
</div>
<div class="form-group">
	<label for="student_group_code" class="col-sm-3 control-label">分组编号，8位字符</label>
	<div class="col-sm-9">
		<input type="text" class="form-control" id="student_group_code"
			name="student_group_code" placeholder="分组编号，8位字符" value="${it.student_group_code}">
	</div>
</div>
<div class="form-group">
	<label for="student_group_name" class="col-sm-3 control-label">组名</label>
	<div class="col-sm-9">
		<input type="text" class="form-control" id="student_group_name"
			name="student_group_name" placeholder="组名" value="${it.student_group_name}">
	</div>
</div>
<div class="form-group">
	<label for="comment" class="col-sm-3 control-label">对实验报告的评语，100字以内！</label>
	<div class="col-sm-9">
		<input type="text" class="form-control" id="comment"
			name="comment" placeholder="对实验报告的评语，100字以内！" value="${it.comment}">
	</div>
</div>
<div class="form-group">
	<label for="mainflow" class="col-sm-3 control-label">实验主要流程、基本操作或核心代码、算法片段</label>
	<div class="col-sm-9">
<textarea class="form-control" id="mainflow" name="mainflow" style="width:100%;height:400px;visibility:hidden;">${it.mainflow}</textarea>
	</div>
</div>
<div class="form-group">
	<label for="report" class="col-sm-3 control-label">实验报告，用xml记录实验结果</label>
	<div class="col-sm-9">
<textarea class="form-control" id="report" name="report" style="width:100%;height:400px;visibility:hidden;">${it.report}</textarea>
	</div>
</div>
<div class="form-group">
	<label for="result" class="col-sm-3 control-label">实验结果的分析与评价</label>
	<div class="col-sm-9">
<textarea class="form-control" id="result" name="result" style="width:100%;height:400px;visibility:hidden;">${it.result}</textarea>
	</div>
</div>
<div class="form-group d_t_dater">
	<label for="submit_date" class="col-sm-3 control-label">实验提交时间</label>
	<div class="col-sm-9">
		<div class="input-group">
	<span class="input-group-addon" style="cursor: pointer;"
	onclick="$.jeDate('#submit_date',{trigger:false,format: 'YYYY-MM-DD hh:mm:ss'})">实验提交时间</span>
<input placeholder="实验提交时间" type="text"
	class="form-control" id="submit_date"
	name="submit_date"
	<c:if test="${it.submit != 0}">
	value="<fmt:formatDate pattern='yyyy-MM-dd HH:mm:ss' value='${it.submit_date}' />"
	</c:if>
	readonly>
		</div>
	</div>
</div>
<div class="form-group">
	<label for="scorescript" class="col-sm-3 control-label">成绩描述：优秀/良好/中等/及格/不及格</label>
	<div class="col-sm-9">
		<input type="text" class="form-control" id="scorescript"
			name="scorescript" placeholder="成绩描述：优秀/良好/中等/及格/不及格" value="${it.scorescript}">
	</div>
</div>
<div class="form-group d_t_dater">
	<label for="create_gmt_date" class="col-sm-3 control-label">创建时间</label>
	<div class="col-sm-9">
		<div class="input-group">
	<span class="input-group-addon" style="cursor: pointer;"
	onclick="$.jeDate('#create_gmt_date',{trigger:false,format: 'YYYY-MM-DD hh:mm:ss'})">创建时间</span>
<input placeholder="创建时间" type="text"
	class="form-control" id="create_gmt_date"
	name="create_gmt_date"
	<c:if test="${it.create_gmt != 0}">
	value="<fmt:formatDate pattern='yyyy-MM-dd HH:mm:ss' value='${it.create_gmt_date}' />"
	</c:if>
	readonly>
		</div>
	</div>
</div>
<div class="form-group d_t_dater">
	<label for="update_gmt_date" class="col-sm-3 control-label">修改时间</label>
	<div class="col-sm-9">
		<div class="input-group">
	<span class="input-group-addon" style="cursor: pointer;"
	onclick="$.jeDate('#update_gmt_date',{trigger:false,format: 'YYYY-MM-DD hh:mm:ss'})">修改时间</span>
<input placeholder="修改时间" type="text"
	class="form-control" id="update_gmt_date"
	name="update_gmt_date"
	<c:if test="${it.update_gmt != 0}">
	value="<fmt:formatDate pattern='yyyy-MM-dd HH:mm:ss' value='${it.update_gmt_date}' />"
	</c:if>
	readonly>
		</div>
	</div>
</div>
<div class="form-group">
	<label for="wechat_openid" class="col-sm-3 control-label">微信openid</label>
	<div class="col-sm-9">
		<input type="text" class="form-control" id="wechat_openid"
			name="wechat_openid" placeholder="微信openid" value="${it.wechat_openid}">
	</div>
</div>
<div class="form-group">
	<label for="experiment_title" class="col-sm-3 control-label">实验标题</label>
	<div class="col-sm-9">
		<input type="text" class="form-control" id="experiment_title"
			name="experiment_title" placeholder="实验标题" value="${it.experiment_title}">
	</div>
</div>
<div class="form-group">
	<label for="experiment_content" class="col-sm-3 control-label">实验内容</label>
	<div class="col-sm-9">
<textarea class="form-control" id="experiment_content" name="experiment_content" style="width:100%;height:400px;visibility:hidden;">${it.experiment_content}</textarea>
	</div>
</div>
<div class="form-group">
	<label for="experiment_purposes_requirement" class="col-sm-3 control-label">实验目的及要求</label>
	<div class="col-sm-9">
<textarea class="form-control" id="experiment_purposes_requirement" name="experiment_purposes_requirement" style="width:100%;height:400px;visibility:hidden;">${it.experiment_purposes_requirement}</textarea>
	</div>
</div>
<div class="form-group">
	<label for="subject_name" class="col-sm-3 control-label">科目标题</label>
	<div class="col-sm-9">
		<input type="text" class="form-control" id="subject_name"
			name="subject_name" placeholder="科目标题" value="${it.subject_name}">
	</div>
</div>
<!-- selectbox begin -->
<div class="form-group">
	<label for="subject_id" class="col-sm-3 control-label">学科</label>
	<div class="col-sm-9">
		<select class="selectbox" id="subject_id" name="subject_id"  style="width:100%;">
			<c:forEach var="item" items="${subjectlist}" varStatus="i">
				<option value="${item.id}"
					<c:if test="${item.id==it.subject_id}">selected</c:if>>${item.name}</option>
			</c:forEach>
		</select>
	</div>
</div>
<!-- selectbox end -->
<!-- radio begin -->
			<c:forEach var="item" items="${subjectlist}" varStatus="i">
			<div class="radio3 radio-check radio-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} radio-inline">
				<input type="radio" id="subject_id${i.count}" name="subject_id" value="${item.id}" <c:if test="${item.id==it.subject_id}">checked</c:if>> <label for="subject_id${i.count}">${item.name}</label>
			</div>
			</c:forEach>
<!-- radio end -->
<!-- selectbox begin -->
<div class="form-group">
	<label for="user_id" class="col-sm-3 control-label">教师</label>
	<div class="col-sm-9">
		<select class="selectbox" id="user_id" name="user_id"  style="width:100%;">
			<c:forEach var="item" items="${userlist}" varStatus="i">
				<option value="${item.id}"
					<c:if test="${item.id==it.user_id}">selected</c:if>>${item.name}</option>
			</c:forEach>
		</select>
	</div>
</div>
<!-- selectbox end -->
<!-- radio begin -->
			<c:forEach var="item" items="${userlist}" varStatus="i">
			<div class="radio3 radio-check radio-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} radio-inline">
				<input type="radio" id="user_id${i.count}" name="user_id" value="${item.id}" <c:if test="${item.id==it.user_id}">checked</c:if>> <label for="user_id${i.count}">${item.name}</label>
			</div>
			</c:forEach>
<!-- radio end -->
<div class="form-group d_t_dater">
	<label for="closing_gmt_date" class="col-sm-3 control-label"></label>
	<div class="col-sm-9">
		<div class="input-group">
	<span class="input-group-addon" style="cursor: pointer;"
	onclick="$.jeDate('#closing_gmt_date',{trigger:false,format: 'YYYY-MM-DD hh:mm:ss'})"></span>
<input placeholder="" type="text"
	class="form-control" id="closing_gmt_date"
	name="closing_gmt_date"
	<c:if test="${it.closing_gmt != 0}">
	value="<fmt:formatDate pattern='yyyy-MM-dd HH:mm:ss' value='${it.closing_gmt_date}' />"
	</c:if>
	readonly>
		</div>
	</div>
</div>
<div class="form-group d_t_dater">
	<label for="opening_gmt_date" class="col-sm-3 control-label"></label>
	<div class="col-sm-9">
		<div class="input-group">
	<span class="input-group-addon" style="cursor: pointer;"
	onclick="$.jeDate('#opening_gmt_date',{trigger:false,format: 'YYYY-MM-DD hh:mm:ss'})"></span>
<input placeholder="" type="text"
	class="form-control" id="opening_gmt_date"
	name="opening_gmt_date"
	<c:if test="${it.opening_gmt != 0}">
	value="<fmt:formatDate pattern='yyyy-MM-dd HH:mm:ss' value='${it.opening_gmt_date}' />"
	</c:if>
	readonly>
		</div>
	</div>
</div>
<div class="form-group">
	<label for="curriculum_student_groupid" class="col-sm-3 control-label">班级</label>
	<div class="col-sm-9">
		<input type="text" class="form-control restrictnumber" id="curriculum_student_groupid"
			name="curriculum_student_groupid" placeholder="班级" value="${it.curriculum_student_groupid}">
	</div>
</div>
<!-- selectbox begin -->
<div class="form-group">
	<label for="student_group_id" class="col-sm-3 control-label">分组id</label>
	<div class="col-sm-9">
		<select class="selectbox" id="student_group_id" name="student_group_id"  style="width:100%;">
			<c:forEach var="item" items="${student_grouplist}" varStatus="i">
				<option value="${item.id}"
					<c:if test="${item.id==it.student_group_id}">selected</c:if>>${item.name}</option>
			</c:forEach>
		</select>
	</div>
</div>
<!-- selectbox end -->
<!-- radio begin -->
			<c:forEach var="item" items="${student_grouplist}" varStatus="i">
			<div class="radio3 radio-check radio-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} radio-inline">
				<input type="radio" id="student_group_id${i.count}" name="student_group_id" value="${item.id}" <c:if test="${item.id==it.student_group_id}">checked</c:if>> <label for="student_group_id${i.count}">${item.name}</label>
			</div>
			</c:forEach>
<!-- radio end -->
<div class="form-group">
	<label for="reviewstate" class="col-sm-3 control-label">评阅状态1已评,2待评</label>
	<div class="col-sm-9">
		<input type="text" class="form-control restrictnumber" id="reviewstate"
			name="reviewstate" placeholder="评阅状态1已评,2待评" value="${it.reviewstate}">
	</div>
</div>
<div class="form-group">
	<label for="experiment_curriculumid" class="col-sm-3 control-label"></label>
	<div class="col-sm-9">
		<input type="text" class="form-control restrictnumber" id="experiment_curriculumid"
			name="experiment_curriculumid" placeholder="" value="${it.experiment_curriculumid}">
	</div>
</div>
<div class="form-group">
	<div class="col-sm-offset-3 col-sm-9">
		<button type="submit" class="btn btn-success">更新</button>
	</div>
</div>
										</form>
									</div>
								</div>
							</div>
						</div>
					</c:when>
				</c:choose>
				<!-- content end -->
				<jsp:include page="../inc/bsa_foot.jsp"></jsp:include>
			</div>
			<!-- /. PAGE INNER  -->
		</div>
	</div>
	<c:if test="${operate != null}">
		<script type="text/javascript" src="bssets/jedate/jquery.jedate.js"></script>
		<script type="text/javascript">
			$(document).ready(function() {
				//------------
				$("#create_gmt_date").jeDate({
					format : "YYYY-MM-DD hh:mm:ss"
				});
				$("#update_gmt_date").jeDate({
					format : "YYYY-MM-DD hh:mm:ss"
				});
				//------------
				$("#form1").submit(function(e) {
					if ($("#id").val() == '') {
						alert("必须输入！");
						$("#id").focus();
						return false;
					}
					if ($("#student_id").val() == '') {
						alert("必须输入！");
						$("#student_id").focus();
						return false;
					}
					if ($("#experiment_id").val() == '') {
						alert("实验id必须输入！");
						$("#experiment_id").focus();
						return false;
					}
					if ($("#curriculum_id").val() == '') {
						alert("必须输入！");
						$("#curriculum_id").focus();
						return false;
					}
					if ($("#truename").val() == '') {
						alert("用户名称必须输入！");
						$("#truename").focus();
						return false;
					}
					if ($("#sno").val() == '') {
						alert("学号必须输入！");
						$("#sno").focus();
						return false;
					}
					if ($("#sno_exp").val() == '') {
						alert("学号必须输入！");
						$("#sno_exp").focus();
						return false;
					}
					if ($("#classcode").val() == '') {
						alert("学校的班级号，不是系统内的班级号必须输入！");
						$("#classcode").focus();
						return false;
					}
					if ($("#score").val() == '') {
						alert("实验成绩必须输入！");
						$("#score").focus();
						return false;
					}
					if ($("#student_group_is_actived").val() == '') {
						alert("是否可以登录必须输入！");
						$("#student_group_is_actived").focus();
						return false;
					}
					if ($("#student_is_actived").val() == '') {
						alert("冻结账号必须输入！");
						$("#student_is_actived").focus();
						return false;
					}
					if ($("#curriculum_is_actived").val() == '') {
						alert("必须输入！");
						$("#curriculum_is_actived").focus();
						return false;
					}
					if ($("#experiment_curriculum_is_actived").val() == '') {
						alert("必须输入！");
						$("#experiment_curriculum_is_actived").focus();
						return false;
					}
					if ($("#subject_is_actived").val() == '') {
						alert("是否显示必须输入！");
						$("#subject_is_actived").focus();
						return false;
					}
					if ($("#student_group_code").val() == '') {
						alert("分组编号，8位字符必须输入！");
						$("#student_group_code").focus();
						return false;
					}
					if ($("#student_group_name").val() == '') {
						alert("组名必须输入！");
						$("#student_group_name").focus();
						return false;
					}
					if ($("#comment").val() == '') {
						alert("对实验报告的评语，100字以内！必须输入！");
						$("#comment").focus();
						return false;
					}
					if ($("#mainflow").val() == '') {
						alert("实验主要流程、基本操作或核心代码、算法片段必须输入！");
						$("#mainflow").focus();
						return false;
					}
					if ($("#report").val() == '') {
						alert("实验报告，用xml记录实验结果必须输入！");
						$("#report").focus();
						return false;
					}
					if ($("#result").val() == '') {
						alert("实验结果的分析与评价必须输入！");
						$("#result").focus();
						return false;
					}
					if ($("#submit_date").val() == '') {
						alert("实验提交时间必须输入！");
						$("#submit_date").focus();
						return false;
					}
					if ($("#scorescript").val() == '') {
						alert("成绩描述：优秀/良好/中等/及格/不及格必须输入！");
						$("#scorescript").focus();
						return false;
					}
					if ($("#create_gmt_date").val() == '') {
						alert("创建时间必须输入！");
						$("#create_gmt_date").focus();
						return false;
					}
					if ($("#update_gmt_date").val() == '') {
						alert("修改时间必须输入！");
						$("#update_gmt_date").focus();
						return false;
					}
					if ($("#wechat_openid").val() == '') {
						alert("微信openid必须输入！");
						$("#wechat_openid").focus();
						return false;
					}
					if ($("#experiment_title").val() == '') {
						alert("实验标题必须输入！");
						$("#experiment_title").focus();
						return false;
					}
					if ($("#experiment_content").val() == '') {
						alert("实验内容必须输入！");
						$("#experiment_content").focus();
						return false;
					}
					if ($("#experiment_purposes_requirement").val() == '') {
						alert("实验目的及要求必须输入！");
						$("#experiment_purposes_requirement").focus();
						return false;
					}
					if ($("#subject_name").val() == '') {
						alert("科目标题必须输入！");
						$("#subject_name").focus();
						return false;
					}
					if ($("#subject_id").val() == '') {
						alert("学科必须输入！");
						$("#subject_id").focus();
						return false;
					}
					if ($("#user_id").val() == '') {
						alert("教师必须输入！");
						$("#user_id").focus();
						return false;
					}
					if ($("#closing_gmt_date").val() == '') {
						alert("必须输入！");
						$("#closing_gmt_date").focus();
						return false;
					}
					if ($("#opening_gmt_date").val() == '') {
						alert("必须输入！");
						$("#opening_gmt_date").focus();
						return false;
					}
					if ($("#curriculum_student_groupid").val() == '') {
						alert("班级必须输入！");
						$("#curriculum_student_groupid").focus();
						return false;
					}
					if ($("#student_group_id").val() == '') {
						alert("分组id必须输入！");
						$("#student_group_id").focus();
						return false;
					}
					if ($("#reviewstate").val() == '') {
						alert("评阅状态1已评,2待评必须输入！");
						$("#reviewstate").focus();
						return false;
					}
					if ($("#experiment_curriculumid").val() == '') {
						alert("必须输入！");
						$("#experiment_curriculumid").focus();
						return false;
					}

				});
			});
KindEditor.ready(function(K) {
	var editor1 = K.create('textarea[name="mainflow"]', {
		cssPath : '${basePath}bssets/ket/plugins/code/prettify.css',
		uploadJson : '${basePath}admin/uploadfile',
		fileManagerJson : '${basePath}admin/filemanager',
		allowFileManager : true,
		afterCreate : function() {}
	});
	var editor1 = K.create('textarea[name="report"]', {
		cssPath : '${basePath}bssets/ket/plugins/code/prettify.css',
		uploadJson : '${basePath}admin/uploadfile',
		fileManagerJson : '${basePath}admin/filemanager',
		allowFileManager : true,
		afterCreate : function() {}
	});
	var editor1 = K.create('textarea[name="result"]', {
		cssPath : '${basePath}bssets/ket/plugins/code/prettify.css',
		uploadJson : '${basePath}admin/uploadfile',
		fileManagerJson : '${basePath}admin/filemanager',
		allowFileManager : true,
		afterCreate : function() {}
	});
	var editor1 = K.create('textarea[name="experiment_content"]', {
		cssPath : '${basePath}bssets/ket/plugins/code/prettify.css',
		uploadJson : '${basePath}admin/uploadfile',
		fileManagerJson : '${basePath}admin/filemanager',
		allowFileManager : true,
		afterCreate : function() {}
	});
	var editor1 = K.create('textarea[name="experiment_purposes_requirement"]', {
		cssPath : '${basePath}bssets/ket/plugins/code/prettify.css',
		uploadJson : '${basePath}admin/uploadfile',
		fileManagerJson : '${basePath}admin/filemanager',
		allowFileManager : true,
		afterCreate : function() {}
	});
	prettyPrint();
});
		</script>
	</c:if>
	<c:if test="${operate == null}">
		<script type="text/javascript">
//搜索框
$("#searchbtn").click(function() {
	var kw = $.trim($("#kw").val());
	var qs = "";
	var and = "?";
	var student_id = "";
	$('input:checkbox[class=student_id_ck]:checked').each(function(k) {
		if (k == 0) {
			student_id = $(this).val();
		} else {
			student_id += ',' + $(this).val();
		}
	});
	// alert('student_id=' + student_id);
	if (student_id != '') {
		qs += and + "student_id=" + student_id;
		and = "&";
	}
	var experiment_id = "";
	$('input:checkbox[class=experiment_id_ck]:checked').each(function(k) {
		if (k == 0) {
			experiment_id = $(this).val();
		} else {
			experiment_id += ',' + $(this).val();
		}
	});
	// alert('experiment_id=' + experiment_id);
	if (experiment_id != '') {
		qs += and + "experiment_id=" + experiment_id;
		and = "&";
	}
	var curriculum_id = "";
	$('input:checkbox[class=curriculum_id_ck]:checked').each(function(k) {
		if (k == 0) {
			curriculum_id = $(this).val();
		} else {
			curriculum_id += ',' + $(this).val();
		}
	});
	// alert('curriculum_id=' + curriculum_id);
	if (curriculum_id != '') {
		qs += and + "curriculum_id=" + curriculum_id;
		and = "&";
	}
	var subject_id = "";
	$('input:checkbox[class=subject_id_ck]:checked').each(function(k) {
		if (k == 0) {
			subject_id = $(this).val();
		} else {
			subject_id += ',' + $(this).val();
		}
	});
	// alert('subject_id=' + subject_id);
	if (subject_id != '') {
		qs += and + "subject_id=" + subject_id;
		and = "&";
	}
	var user_id = "";
	$('input:checkbox[class=user_id_ck]:checked').each(function(k) {
		if (k == 0) {
			user_id = $(this).val();
		} else {
			user_id += ',' + $(this).val();
		}
	});
	// alert('user_id=' + user_id);
	if (user_id != '') {
		qs += and + "user_id=" + user_id;
		and = "&";
	}
	var student_group_id = "";
	$('input:checkbox[class=student_group_id_ck]:checked').each(function(k) {
		if (k == 0) {
			student_group_id = $(this).val();
		} else {
			student_group_id += ',' + $(this).val();
		}
	});
	// alert('student_group_id=' + student_group_id);
	if (student_group_id != '') {
		qs += and + "student_group_id=" + student_group_id;
		and = "&";
	}
	if (kw != '') {
		qs += and + "kw=" + kw;
		and = "&";
	}
	// alert("qs=" + qs);
	$(location).attr('href', '${basePath}${pagename}' + qs);
});

		</script>
	</c:if>
	
</body>
</html>


