//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- Remarks: ServiceImpl
//-- Date Generated: 2020-10-09 10:47:59
//-----------------------------

package tpa.service.impl;

import tpa.entity.Link_role_permit;
import tpa.mapper.Link_role_permitMapper;
import tpa.service.ILink_role_permitService;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import sld.webutils.Util;

import java.util.*;



import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
@Service("link_role_permitService")
public class Link_role_permitServiceImpl extends ServiceImpl<Link_role_permitMapper, Link_role_permit> implements ILink_role_permitService {

	@Autowired
	private Link_role_permitMapper link_role_permitMapper;
	@Override
	public Integer max(String fieldname) {
		return link_role_permitMapper.max(fieldname);
	}
	@Override
	public Map<String, Integer> statMapByFieldname(String fieldname) {
		return Util.listmapToMap(link_role_permitMapper.statMapByFieldname(fieldname));
	}
	@Override
	public void updatePlus(String fieldname, Integer addend, Integer id) {
		link_role_permitMapper.updatePlus(fieldname, addend, id);
	}
}
