//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- Remarks: ServiceImpl
//-- Date Generated: 2020-10-09 10:48:00
//-----------------------------

package tpa.service.impl;

import tpa.entity.Link_user_role;
import tpa.mapper.Link_user_roleMapper;
import tpa.service.ILink_user_roleService;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import sld.webutils.Util;

import java.util.*;



import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
@Service("link_user_roleService")
public class Link_user_roleServiceImpl extends ServiceImpl<Link_user_roleMapper, Link_user_role> implements ILink_user_roleService {

	@Autowired
	private Link_user_roleMapper link_user_roleMapper;
	@Override
	public Integer max(String fieldname) {
		return link_user_roleMapper.max(fieldname);
	}
	@Override
	public Map<String, Integer> statMapByFieldname(String fieldname) {
		return Util.listmapToMap(link_user_roleMapper.statMapByFieldname(fieldname));
	}
	@Override
	public void updatePlus(String fieldname, Integer addend, Integer id) {
		link_user_roleMapper.updatePlus(fieldname, addend, id);
	}
}
