//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- Remarks: ServiceImpl
//-- Date Generated: 2020-10-09 10:48:00
//-----------------------------

package tpa.service.impl;

import tpa.entity.Student_group;
import tpa.mapper.Student_groupMapper;
import tpa.service.IStudent_groupService;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import sld.webutils.Util;

import java.util.*;



import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
@Service("student_groupService")
public class Student_groupServiceImpl extends ServiceImpl<Student_groupMapper, Student_group> implements IStudent_groupService {

	@Autowired
	private Student_groupMapper student_groupMapper;
	@Override
	public Integer max(String fieldname) {
		return student_groupMapper.max(fieldname);
	}
	@Override
	public Map<String, Integer> statMapByFieldname(String fieldname) {
		return Util.listmapToMap(student_groupMapper.statMapByFieldname(fieldname));
	}
	@Override
	public void updatePlus(String fieldname, Integer addend, Integer id) {
		student_groupMapper.updatePlus(fieldname, addend, id);
	}
}
