//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- Remarks: ServiceImpl
//-- Date Generated: 2020-10-09 10:48:00
//-----------------------------

package tpa.service.impl;

import org.springframework.beans.factory.annotation.Qualifier;
import tpa.entity.Student;
import tpa.mapper.StudentMapper;
import tpa.service.IStudentService;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import sld.webutils.Util;

import java.util.*;



import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
@Service("studentService")
public class StudentServiceImpl extends ServiceImpl<StudentMapper, Student> implements IStudentService {

	@Autowired
	private StudentMapper studentMapper;
	@Override
	public Integer max(String fieldname) {
		return studentMapper.max(fieldname);
	}
	@Override
	public Map<String, Integer> statMapByFieldname(String fieldname) {
		return Util.listmapToMap(studentMapper.statMapByFieldname(fieldname));
	}
	@Override
	public void updatePlus(String fieldname, Integer addend, Integer id) {
		studentMapper.updatePlus(fieldname, addend, id);
	}
	
	
	@Override
	public List<Student> listStudentByCurriculumid(Integer curriculumid) {

		return studentMapper.listStudentByCurriculumid(curriculumid);
	}

//	//根据学生学号查询学生--julius
//	@Override
//	public Student getStudentBySno(String sno) {
//		return studentMapper.getStudentBySno(sno);
//	}


}
