//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- Remarks: ServiceImpl
//-- Date Generated: 2020-10-09 10:48:00
//-----------------------------

package tpa.service.impl;

import tpa.entity.Vevaluation_point;
import tpa.mapper.Vevaluation_pointMapper;
import tpa.service.IVevaluation_pointService;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;

import app.entity.StatEvaluationPoint;

import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import sld.webutils.Util;

import java.util.*;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service("vevaluation_pointService")
public class Vevaluation_pointServiceImpl extends ServiceImpl<Vevaluation_pointMapper, Vevaluation_point>
		implements IVevaluation_pointService {

	@Autowired
	private Vevaluation_pointMapper vevaluation_pointMapper;

	@Override
	public Integer max(String fieldname) {
		return vevaluation_pointMapper.max(fieldname);
	}

	@Override
	public Map<String, Integer> statMapByFieldname(String fieldname) {
		return Util.listmapToMap(vevaluation_pointMapper.statMapByFieldname(fieldname));
	}

	@Override
	public void updatePlus(String fieldname, Integer addend, Integer id) {
		vevaluation_pointMapper.updatePlus(fieldname, addend, id);
	}

	public List<StatEvaluationPoint> statEvaluationPointByMap() {
		return vevaluation_pointMapper.statEvaluationPointByMap();
	}
}
