//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- Remarks: ServiceImpl
//-- Date Generated: 2020-10-09 10:48:00
//-----------------------------

package tpa.service.impl;

import tpa.entity.Vexperiment_record;
import tpa.mapper.Vexperiment_recordMapper;
import tpa.service.IVexperiment_recordService;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import sld.webutils.Util;

import java.util.*;



import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
@Service("vexperiment_recordService")
public class Vexperiment_recordServiceImpl extends ServiceImpl<Vexperiment_recordMapper, Vexperiment_record> implements IVexperiment_recordService {

	@Autowired
	private Vexperiment_recordMapper vexperiment_recordMapper;
	@Override
	public Integer max(String fieldname) {
		return vexperiment_recordMapper.max(fieldname);
	}
	@Override
	public Map<String, Integer> statMapByFieldname(String fieldname) {
		return Util.listmapToMap(vexperiment_recordMapper.statMapByFieldname(fieldname));
	}
	@Override
	public void updatePlus(String fieldname, Integer addend, Integer id) {
		vexperiment_recordMapper.updatePlus(fieldname, addend, id);
	}
}
