//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- Remarks: ServiceImpl
//-- Date Generated: 2020-10-09 10:48:00
//-----------------------------

package tpa.service.impl;

import tpa.entity.Vlink_student2group;
import tpa.mapper.Vlink_student2groupMapper;
import tpa.service.IVlink_student2groupService;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import sld.webutils.Util;

import java.util.*;



import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
@Service("vlink_student2groupService")
public class Vlink_student2groupServiceImpl extends ServiceImpl<Vlink_student2groupMapper, Vlink_student2group> implements IVlink_student2groupService {

	@Autowired
	private Vlink_student2groupMapper vlink_student2groupMapper;
	@Override
	public Integer max(String fieldname) {
		return vlink_student2groupMapper.max(fieldname);
	}
	@Override
	public Map<String, Integer> statMapByFieldname(String fieldname) {
		return Util.listmapToMap(vlink_student2groupMapper.statMapByFieldname(fieldname));
	}
	@Override
	public void updatePlus(String fieldname, Integer addend, Integer id) {
		vlink_student2groupMapper.updatePlus(fieldname, addend, id);
	}
}
