<!------------------------------->
<!---- Generated By Denny(luhox@qq.com), cslite for sm -->
<!---- Remarks: ItemListHTML-->
<!---- Date Generated: 2019-04-07 17:14:57-->
<!------------------------------->
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<c:set var="searchpanel" value="true"></c:set>
<c:set var="uploadfile" value="true"></c:set>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<jsp:include page="../inc/bsa_head.jsp"></jsp:include>
<!-- Custom Styles-->
<link href="bssets/css/bsat1-style.css" rel="stylesheet" />
<title>${pagetitle}-${appName}</title>
</head>
<body>
	<div id="wrapper">
		<jsp:include page="../inc/bsa_navtop.jsp"></jsp:include>
		<!--/. NAV TOP  -->
		<jsp:include page="../inc/bsa_navside.jsp"></jsp:include>
		<!-- /. NAV SIDE  -->
		<div id="page-wrapper">
			<div class="header">
				<h3 class="page-header">
					${pagetitle} <small>${subtitle}</small>
				</h3>
			</div>
			<div id="page-inner">
				<!-- content start -->
				<c:choose>
					<c:when test="${operate == null}">

						<!-- div Tables -->
						<div class="panel panel-default">
							<!--  <div class="panel-heading">${tabletitle}</div> -->
							<div class="row margin-xs">
								<div class="col-xs-12 col-sm-12 col-md-1 col-lg-1">
									<div>
										<a href="${pagename}?operate=add" class="btn btn-primary">新增</a>
									</div>
								</div>
								<c:if test="${searchpanel=='true'}">
									<div class="col-xs-12 col-sm-12 col-md-11 col-lg-11">
										<div class="row">
											<div class="col-sm-12">
												<button class="btn btn-success" type="button"
													data-toggle="collapse" data-target="#searchPanel"
													aria-expanded="false" aria-controls="searchPanel">
													筛选条件</button>
												<div id="searchPanel"
													<c:if test="${kw != null }">class="collapse in form-inline" </c:if>
													<c:if test="${kw == null }">class="collapse form-inline" </c:if>>
													<div class="well">
														<!-- 面板 -->
														<div class="row">
															<div
																class="col-xs-4 col-sm-3 col-md-2 col-lg-2 text-right margin-top-xs">
																模糊查询：</div>
															<div class="col-xs-6 col-sm-4 col-md-4 col-lg-3">
																<div class="form-group">
																	<input style="width: 100%;" type="text"
																		class="form-control" id="kw" name="kw" value="${kw}"
																		placeholder="模糊查询">
																</div>
															</div>
														</div>
														<div class="clearfix showborder-top"></div>

														<div class="clearfix"></div>
														<div class="row">
															<div class="col-xs-12 col-sm-12 col-md-4 col-lg-3">
																<button id="searchbtn" class="btn btn-warning">搜索</button>
															</div>
															<div class="col-xs-12 col-sm-12 col-md-4 col-lg-3">
																<button class="btn btn-danger canclesearch">清除搜索条件</button>
															</div>
														</div>
														<!-- /面板 -->
													</div>

												</div>

											</div>
										</div>
									</div>
								</c:if>
							</div>
							<jsp:include page="../inc/pager.jsp"></jsp:include>
							<!-- div表格  (中大屏幕，表格显示) begin -->

							<!-- Advanced Tables -->
							<div
								class="panel panel-default  visible-md-block visible-lg-block">
								<!-- <div class="panel-heading">${tabletitle}</div> -->
								<div class="row">
									<div class="col-md-12">
										<div class="panel-body">
											<div class="table-responsive">
												<table
													class="table table-striped table-bordered table-hover"
													id="dataTables-example">
													<thead>
														<tr class="bg-blue">
															<th>序号</th>
															<th>许可名称</th>
															<th>许可代码</th>
															<th>操作</th>
														</tr>
													</thead>
													<tbody>
														<c:forEach var="it" items="${list}" varStatus="index">
															<tr>
																<td id="t${it.id}">${index.count+(pager.current - 1) * pager.size}</td>
																<td>${it.name}</td>
																<td>${it.code}</td>
																<td><button value="${it.id}"
																		class="edititem btn-sm btn btn-success">编辑</button>
																	<button value="${it.id}"
																		class="deleteitem btn btn-sm btn-danger">删除</button></td>
															</tr>
														</c:forEach>
													</tbody>
												</table>
											</div>
										</div>
									</div>
								</div>
							</div>
							<!--End Advanced Tables -->
							<!-- div表格  (中大屏幕，表格显示) end -->
							<!-- div表格  (小屏幕，类卡片显示) begin -->
							<div class="panel-body visible-xs-block visible-sm-block">
								<div class="row">
									<c:forEach var="it" items="${list}" varStatus="index">
										<div class="col-xs-12 col-sm-6">
											<div class="row showbd margin-xs">
												<div class="col-xs-12 col-sm-12 bg-primary padding-xs"
													id="t${it.id}">
													<h3>${index.count+(pager.current - 1) * pager.size}</h3>
												</div>
												<div class="clearfix"></div>

												<div class="col-xs-12 col-sm-12">${it.id}</div>
												<div class="clearfix"></div>

												<div class="col-xs-12 col-sm-12">${it.target}</div>
												<div class="clearfix"></div>

												<div class="col-xs-12 col-sm-12">${it.operation}</div>
												<div class="clearfix"></div>

												<div class="col-xs-12 col-sm-12">${it.name}</div>
												<div class="clearfix"></div>

												<div class="col-xs-12 col-sm-12">${it.code}</div>
												<div class="clearfix"></div>

												<div class="col-xs-12 col-sm-12">
													<button value="${it.id}" class="edititem btn btn-success">编辑</button>
													<button value="${it.id}" class="deleteitem btn btn-danger">删除</button>
												</div>
											</div>
										</div>
									</c:forEach>
								</div>
							</div>
							<!-- div表格  (小屏幕，类卡片显示) end -->
						</div>
						<!--End div Tables -->
					</c:when>
					<c:when test="${operate == 'add'}">
						<div class="row">
							<div class="col-xs-12">
								<div class="panel panel-default">
									<div class="panel-heading">
										<div class="card-title">
											<div class="title">${formtitle}</div>
										</div>
									</div>
									<div class="panel-body">
										<a class="btn btn-warning" href="${pagename}">放弃保存，直接返回</a>
										<form id="form1" class="form-horizontal" method="post"
											action="${pagename}">
											<input type="hidden" name="operate" value="addform" /> <input
												type="hidden" name="referer" value="${referer}" />
											<div class="form-group">
												<label for="code" class="col-sm-2 control-label">许可信息</label>
												<div class="col-sm-10">
													<input type="text" class="form-control" id="code"
														name="code" placeholder="user:insert/库名:操作" readonly>
												</div>
											</div>
											<div class="form-group">
												<label for="table" class="col-sm-2 control-label">许可表名</label>
												<div class="col-sm-10">
													<select class="selectbox" id="target" name="target"
														style="width: 100%;">
														<c:forEach var="item" items="${dblist}" varStatus="i">
															<option value="${item}">${item}</option>
														</c:forEach>
													</select>
												</div>
											</div>
											<div class="form-group">
												<label for="operation" class="col-sm-2 control-label">许可操作</label>
												<div class="col-sm-10">
													<select class="selectbox" id="operation" name="operation"
														style="width: 100%;">
														<c:set var="arr" value="insert,delete,update,query" />
														<c:forEach var="item" items="${fn:split(arr,',')}"
															begin="0" end="${fn:length(fn:split(arr,','))}" step="1"
															varStatus="i">
															<option value="${item}">${item}</option>
														</c:forEach>
													</select>
												</div>
											</div>

											<div class="form-group">
												<label for="name" class="col-sm-2 control-label">许可名称</label>
												<div class="col-sm-10">
													<input type="text" class="form-control" id="name"
														name="name" placeholder="自定义，例如：更新用户">
												</div>
											</div>
											<div id="submitbtn" class="form-group">
												<div class="col-sm-offset-2 col-sm-10">
													<button type="submit" class="btn btn-success">添加信息</button>
												</div>
											</div>
											<div id="info" class="form-group">
												<div class="col-sm-offset-2 col-sm-10 text-danger">系统中已经包含了该许可，不能重复添加！</div>
											</div>

										</form>
									</div>
								</div>
							</div>
						</div>
					</c:when>
					<c:when test="${operate == 'edit'}">
						<div class="row">
							<div class="col-xs-12">
								<div class="panel panel-default">
									<div class="panel-heading">
										<div class="card-title">
											<div class="title">${formtitle}</div>
										</div>
									</div>
									<div class="panel-body">
										<a class="btn btn-warning" href="${pagename}">放弃保存，直接返回</a>
										<form id="form1" class="form-horizontal" method="post"
											action="${pagename}">
											<input type="hidden" name="operate" value="editform" /> <input
												type="hidden" name="id" value="${it.id}" /> <input
												type="hidden" name="referer" value="${referer}" />
											<div class="form-group">
												<label for="code" class="col-sm-2 control-label">许可信息</label>
												<div class="col-sm-10">
													<input type="text" class="form-control" id="code"
														name="code" placeholder="许可信息(user:delete)角色:操作"
														value="${it.code}" readonly>
												</div>
											</div>
											<div class="form-group">
												<label for="table" class="col-sm-2 control-label">许可表名</label>
												<div class="col-sm-10">
													<select class="selectbox" id="target" name="target"
														style="width: 100%;">
														<c:forEach var="item" items="${dblist}" varStatus="i">
															<option value="${item}"
																<c:if test="${item==it.target}">selected</c:if>>${item}</option>
														</c:forEach>
													</select>
												</div>
											</div>
											<div class="form-group">
												<label for="operation" class="col-sm-2 control-label">许可操作</label>
												<div class="col-sm-10">
													<select class="selectbox" id="operation" name="operation"
														style="width: 100%;">
														<c:set var="arr" value="insert,delete,update,query" />
														<c:forEach var="item" items="${fn:split(arr,',')}"
															begin="0" end="${fn:length(fn:split(arr,','))}" step="1"
															varStatus="i">
															<option value="${item}"
																<c:if test="${item==it.operation}">selected</c:if>>${item}</option>
														</c:forEach>
													</select>
												</div>
											</div>
											<div class="form-group">
												<label for="name" class="col-sm-2 control-label">许可名称</label>
												<div class="col-sm-10">

													<input type="text" class="form-control" id="name"
														name="name" placeholder="许可名称" value="${it.name}">
												</div>
											</div>
											<div id="submitbtn" class="form-group">
												<div class="col-sm-offset-2 col-sm-10">
													<button type="submit" class="btn btn-success">更新信息</button>
												</div>
											</div>
											<div id="info" class="form-group">
												<div class="col-sm-offset-2 col-sm-10 text-danger">系统中已经包含了该许可，不能重复添加！</div>
											</div>
										</form>
									</div>
								</div>
							</div>
						</div>
					</c:when>
				</c:choose>
				<!-- content end -->
				<jsp:include page="../inc/bsa_foot.jsp"></jsp:include>
			</div>
			<!-- /. PAGE INNER  -->
		</div>
	</div>
	<c:if test="${operate != null}">
		<script type="text/javascript" src="bssets/js/uploadheadimg.js"></script>
		<script type="text/javascript" src="bssets/jedate/jquery.jedate.js"></script>
		<script type="text/javascript">
			function updatecode(codestring) {
				//console.log("codestring=" + codestring);
				$("#code").val(codestring);
				//ajax检查当前权限是否已经存在
				$.ajax({
					data : "code=" + codestring
							+ "&operate=${param.operate}&id=${param.id}",
					type : "GET",
					dataType : 'json',
					url : "superadmin/managepermitcheckisexist",
					error : function(data) {
						alert("请刷新后重试！");
						//$("#submitbtn").attr('disabled',false);
					},
					success : function(data) {
						//alert("data.msg:"+data.msg);  
						if (data.msg == 'success') {
							$("#submitbtn").show();
							$("#info").hide();
						} else {
							//alert("data.msg:"+data.msg);
							$("#submitbtn").hide();
							$("#info").show();
						}

					}
				});
			}
			$(document).ready(
					function() {
						//------------
						updatecode($('#target option:selected').val() + ":"
								+ $('#operation option:selected').val());
						$("#target").on(
								'change',
								function() {
									updatecode($('#target option:selected')
											.val()
											+ ":"
											+ $('#operation option:selected')
													.val());
								});
						$("#operation").on(
								'change',
								function() {
									updatecode($('#target option:selected')
											.val()
											+ ":"
											+ $('#operation option:selected')
													.val());
								});
						//------------

						$("#form1").submit(function(e) {
							if ($("#target").val() == '') {
								alert("许可表名:user必须输入！");
								$("#target").focus();
								return false;
							}
							if ($("#operation").val() == '') {
								alert("许可操作:insert必须输入！");
								$("#operation").focus();
								return false;
							}
							if ($("#name").val() == '') {
								alert("许可名称:更新用户必须输入！");
								$("#name").focus();
								return false;
							}
							if ($("#code").val() == '') {
								alert("许可代码(user:insert)库名:操作必须输入！");
								$("#code").focus();
								return false;
							}

						});
					});
		</script>
	</c:if>
	<c:if test="${operate == null}">
		<script type="text/javascript">
			//搜索框
			$("#searchbtn").click(function() {
				var kw = $.trim($("#kw").val());
				var qs = "";
				var and = "?";
				if (kw != '') {
					qs += and + "kw=" + kw;
					and = "&";
				}
				// alert("qs=" + qs);
				$(location).attr('href', '${basePath}${pagename}' + qs);
			});

			$(".members").click(
					function() {
						$(location).attr(
								'href',
								'${basePath}${pagename}?operate=members&id='
										+ $(this).val());
					});
		</script>
	</c:if>

</body>
</html>


