<!------------------------------->
<!---- Generated By Denny(luhox@qq.com), cslite for sm -->
<!---- Remarks: ItemListHTML-->
<!---- Date Generated: 2019-04-01 16:13:15-->
<!------------------------------->
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<c:set var="searchpanel" value="true"></c:set>
<c:set var="uploadfile" value="true"></c:set>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<jsp:include page="../inc/bsa_head.jsp"></jsp:include>
<jsp:include page="../inc/ket.jsp"></jsp:include>
<!-- Custom Styles-->
<link href="bssets/css/bsat1-style.css" rel="stylesheet" />
<title>${pagetitle}-${appName}</title>
</head>
<body>
	<div id="wrapper">
		<jsp:include page="../inc/bsa_navtop.jsp"></jsp:include>
		<!--/. NAV TOP  -->
		<jsp:include page="../inc/bsa_navside.jsp"></jsp:include>
		<!-- /. NAV SIDE  -->
		<div id="page-wrapper">
			<div class="header">
				<h3 class="page-header">
					${pagetitle} <small>${subtitle}</small>
				</h3>
			</div>
			<div id="page-inner">
				<!-- content start -->
				<c:choose>
					<c:when test="${operate == null}">

						<!-- div Tables -->
						<div class="panel panel-default">
							<!--  <div class="panel-heading">${tabletitle}</div> -->
							<div class="row margin-xs">
								<div class="col-xs-12 col-sm-12 col-md-1 col-lg-1">
									<div>
										<a href="${pagename}?operate=add" class="btn btn-primary">新增</a>
									</div>
								</div>
								<c:if test="${searchpanel=='true'}">
									<div class="col-xs-12 col-sm-12 col-md-11 col-lg-11">
										<div class="row">
											<div class="col-sm-12">
												<button class="btn btn-success" type="button"
													data-toggle="collapse" data-target="#searchPanel"
													aria-expanded="false" aria-controls="searchPanel">
													筛选条件</button>
												<div id="searchPanel"
													<c:if test="${kw != null  || column_id_map != null }">class="collapse in form-inline" </c:if>
													<c:if test="${kw == null  && column_id_map == null }">class="collapse form-inline" </c:if>>
													<div class="well">
														<!-- 面板 -->
														<div class="row">
															<div
																class="col-xs-4 col-sm-3 col-md-2 col-lg-2 text-right margin-top-xs">
																模糊查询：</div>
															<div class="col-xs-6 col-sm-4 col-md-4 col-lg-3">
																<div class="form-group">
																	<input style="width: 100%;" type="text"
																		class="form-control" id="kw" name="kw" value="${kw}"
																		placeholder="模糊查询">
																</div>
															</div>
														</div>
														<div class="clearfix showborder-top"></div>
														<!-- 搜索条件：栏目id -->
														<div class="row">
															<div
																class="col-xs-4 col-sm-3 col-md-2 col-lg-2 text-right margin-top-xs">
																栏目:</div>
															<c:forEach var="item" items="${columninfolist}"
																varStatus="i">
																<div class="col-xs-4 col-sm-3 col-md-3 col-lg-3">
																	<div
																		class="checkbox3 checkbox-round checkbox-check checkbox-light">
																		<input value="${item.id}" id="column_id${i.count}"
																			class="column_id_ck" type="checkbox"
																			<c:if test="${column_id_map.get(item.id) != null}">checked</c:if>>
																		<label for="column_id${i.count}">
																			${item.name} </label>
																	</div>
																</div>
																<div class="visible-lg-block">
																	<c:if test="${i.count % 3==0}">
																		<div class="clearfix"></div>
																		<div class="col-lg-2"></div>
																	</c:if>
																</div>
																<div class="visible-md-block">
																	<c:if test="${i.count % 3==0}">
																		<div class="clearfix"></div>
																		<div class="col-md-2"></div>
																	</c:if>
																</div>
																<div class="visible-sm-block">
																	<c:if test="${i.count % 3==0}">
																		<div class="clearfix"></div>
																		<div class="col-sm-3"></div>
																	</c:if>
																</div>
																<div class="visible-xs-block">
																	<c:if test="${i.count % 2==0}">
																		<div class="clearfix"></div>
																		<div class="col-xs-4"></div>
																	</c:if>
																</div>
															</c:forEach>
														</div>
														<div class="clearfix showborder-top"></div>
														<!-- /搜索条件：栏目id -->

														<div class="clearfix"></div>
														<div class="row">
															<div class="col-xs-12 col-sm-12 col-md-4 col-lg-3">
																<button id="searchbtn" class="btn btn-warning">搜索</button>
															</div>
															<div class="col-xs-12 col-sm-12 col-md-4 col-lg-3">
																<button class="btn btn-danger canclesearch">清除搜索条件</button>
															</div>
														</div>
														<!-- /面板 -->
													</div>

												</div>

											</div>
										</div>
									</div>
								</c:if>
							</div>
							<jsp:include page="../inc/pager.jsp"></jsp:include>
							<!-- div表格  (中大屏幕，表格显示) begin -->

							<!-- Advanced Tables -->
							<div
								class="panel panel-default  visible-md-block visible-lg-block">
								<!-- <div class="panel-heading">${tabletitle}</div> -->
								<div class="row">
									<div class="col-md-12">
										<div class="panel-body">
											<div class="table-responsive">
												<table
													class="table table-striped table-bordered table-hover"
													id="dataTables-example">
													<thead>
														<tr class="bg-blue">
															<th>序号</th>
															<th>封面图片</th>
															<th>标题</th>
															<th>所属栏目</th>
															<th>作者</th>
															<th>点击量</th>
															<th>创建时间</th>
															<th>置顶到期</th>
															<th>是否激活</th>
															<th>操作</th>
														</tr>
													</thead>
													<tbody>
														<c:forEach var="it" items="${list}" varStatus="index">
															<tr>
																<td id="t${it.id}">${index.count+(pager.current - 1) * pager.size}</td>
																<td><img style="width: 60px;" src="${it.faceimage}"></td>
																<td><a target="_blank" href="${basePath}shop/a?id=${it.id}">${it.title}</a></td>
																<c:forEach var="item" items="${columninfolist}"
																	varStatus="i">
																	<c:if test="${item.id==it.column_id}">
																		<td>${item.name}</td>
																	</c:if>
																</c:forEach>
																<td>${it.author}</td>
																<td>${it.hitcount}</td>
																<td><c:if test="${it.create_gmt !=0}">
																		<fmt:formatDate pattern="yyyy-MM-dd"
																			value="${it.create_gmt_date}" />
																	</c:if></td>
																<td><c:if test="${it.toptill !=0}">
																		<fmt:formatDate pattern="yyyy-MM-dd"
																			value="${it.toptill_date}" />
																	</c:if></td>
																<td><c:choose>
																		<c:when test="${it.article_is_actived}">
																			<a
																				href="${basePath}${pagename}?operate=hideitem&id=${it.id}"><img
																				alt="" src="bssets/i/greendot.png"></a>
																		</c:when>
																		<c:when test="${it.article_is_actived==false}">
																			<a
																				href="${basePath}${pagename}?operate=showitem&id=${it.id}"><img
																				alt="" src="bssets/i/reddot.png"></a>
																		</c:when>
																	</c:choose></td>
																<td><shiro:hasRole name="articlepublisher">
																		<button value="${it.id}"
																			class="edititem btn-sm btn btn-success">编辑</button>
																		<button value="${it.id}"
																			class="deleteitem btn btn-sm btn-danger">删除</button>
																	</shiro:hasRole></td>
															</tr>
														</c:forEach>
													</tbody>
												</table>
											</div>
										</div>
									</div>
								</div>
							</div>
							<!--End Advanced Tables -->
							<!-- div表格  (中大屏幕，表格显示) end -->
							<!-- div表格  (小屏幕，类卡片显示) begin -->
							<div class="panel-body visible-xs-block visible-sm-block">
								<div class="row">
									<c:forEach var="it" items="${list}" varStatus="index">
										<div class="col-xs-12 col-sm-6">
											<div class="row showbd margin-xs">
												<div class="col-xs-12 col-sm-12 bg-primary padding-xs"
													id="t${it.id}">
													<h3>${index.count+(pager.current - 1) * pager.size}</h3>
												</div>
												<div class="clearfix"></div>

												<div class="col-xs-12 col-sm-12">
													<img style="width: 60px;" src="${it.faceimage}">
												</div>
												<div class="clearfix"></div>

												<div class="col-xs-12 col-sm-12">
													<a target="_blank" href="a?id=${it.id}">${it.title}</a>
												</div>
												<div class="clearfix"></div>



												<div class="col-xs-12 col-sm-12">
													<c:forEach var="item" items="${columninfolist}"
														varStatus="i">
														<c:if test="${item.id==it.column_id}">
															<td>${item.name}</td>
														</c:if>
													</c:forEach>
												</div>
												<div class="clearfix"></div>


												<div class="col-xs-12 col-sm-12">${it.author}</div>
												<div class="clearfix"></div>

												<div class="col-xs-12 col-sm-12">${it.hitcount}</div>
												<div class="clearfix"></div>

												<div class="col-xs-12 col-sm-12">
													<c:if test="${it.create_gmt !=0}">
														<fmt:formatDate pattern="yyyy-MM-dd"
															value="${it.create_gmt_date}" />
													</c:if>
												</div>
												<div class="clearfix"></div>

												<div class="col-xs-12 col-sm-12">
													<c:if test="${it.toptill !=0}">
														<fmt:formatDate pattern="yyyy-MM-dd"
															value="${it.toptill_date}" />
													</c:if>
												</div>
												<div class="clearfix"></div>

												<div class="col-xs-12 col-sm-12">${it.article_is_actived}</div>
												<div class="clearfix"></div>

												<div class="col-xs-12 col-sm-12">
													<button value="${it.id}" class="edititem btn btn-success">编辑</button>
													<button value="${it.id}" class="deleteitem btn btn-danger">删除</button>
												</div>
											</div>
										</div>
									</c:forEach>
								</div>
							</div>
							<!-- div表格  (小屏幕，类卡片显示) end -->
						</div>
						<!--End div Tables -->
					</c:when>
					<c:when test="${operate == 'add'}">
						<div class="row">
							<div class="col-xs-12">
								<div class="panel panel-default">
									<div class="panel-heading">
										<div class="card-title">
											<div class="title">${formtitle}</div>
										</div>
									</div>
									<div class="panel-body">
										<a class="btn btn-warning" href="${pagename}">放弃保存，直接返回</a>
										<form id="form1" class="form-horizontal" method="post"
											action="${pagename}">
											<input type="hidden" name="operate" value="addform" /> <input
												type="hidden" name="referer" value="${referer}" />
											<!-- radio begin -->
											<div class="form-group">
												<label for="column_id" class="col-sm-2 control-label">栏目名称</label>
												<div class="col-sm-10">

<c:forEach var="item" items="${columnlist}" varStatus="i">
	<div class="radio3 radio-check radio-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} radio-inline">
		<input type="radio" id="column_id${i.count}" name="column_id" value="${item.id}"
			<c:if test="${i.count==1}">checked</c:if>> <label for="column_id${i.count}">${item.name}</label>
	</div>
</c:forEach>


												</div>
											</div>
											<!-- radio end -->
											<div class="form-group">
												<label for="title" class="col-sm-2 control-label">文章标题</label>
												<div class="col-sm-10">
													<input type="text" class="form-control" id="title"
														name="title" placeholder="文章的标题">
												</div>
											</div>
											<div class="form-group d_t_dater">
												<label for="toptill_date" class="col-sm-2 control-label">置顶到期</label>
												<div class="col-sm-10">
													<div class="input-group">
														<span class="input-group-addon" style="cursor: pointer;"
															onclick="$.jeDate('#toptill_date',{trigger:false,format: 'YYYY-MM-DD hh:mm:ss'})">置顶到期时间</span>
														<input placeholder="置顶到期时间" type="text" value="${toptill_date}"
															class="form-control" id="toptill_date"
															name="toptill_date" readonly>
													</div>
												</div>
											</div>
											<div class="form-group">
												<label for="face_img" class="col-sm-2 control-label">封面图片</label>
												<div class="col-sm-10">
													<input type="hidden" id="faceimage" name="faceimage" /> <img
														id="faceimage2" src="" alt="" width="100" /> <input
														type="button" id="face_img_btn" value="点击选择封面图片" />（请在已经上传的图片空间中选择，无需指定大小和其他设置！）
												</div>
											</div>
											<div class="form-group">
												<label for="author" class="col-sm-2 control-label">作者</label>
												<div class="col-sm-10">
													<input type="text" class="form-control" id="author" value="${author}"
														name="author" placeholder="作者">
												</div>
											</div>
											<div class="form-group">
												<label for="content" class="col-sm-2 control-label">文章内容</label>
												<div class="col-sm-10">
													<textarea class="form-control" id="content" name="content"
														style="width: 100%; height: 400px; visibility: hidden;"></textarea>
												</div>
											</div>
											<div class="form-group">
												<div class="col-sm-offset-2 col-sm-10">
													<button type="submit" class="btn btn-success">添加文章</button>
												</div>
											</div>
										</form>
									</div>
								</div>
							</div>
						</div>
					</c:when>
					<c:when test="${operate == 'edit'}">
						<div class="row">
							<div class="col-xs-12">
								<div class="panel panel-default">
									<div class="panel-heading">
										<div class="card-title">
											<div class="title">${formtitle}</div>
										</div>
									</div>
									<div class="panel-body">
										<a class="btn btn-warning" href="${pagename}">放弃保存，直接返回</a>
										<form id="form1" class="form-horizontal" method="post"
											action="${pagename}">
											<input type="hidden" name="operate" value="editform" /> <input
												type="hidden" name="id" value="${it.id}" /> <input
												type="hidden" name="referer" value="${referer}" />
											<!-- radio begin -->
											<div class="form-group">
												<label for="column_id" class="col-sm-2 control-label">栏目名称</label>
												<div class="col-sm-10">

<c:forEach var="item" items="${columnlist}" varStatus="i">
	<div class="radio3 radio-check radio-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} radio-inline">
		<input type="radio" id="column_id${i.count}" name="column_id" value="${item.id}"
			<c:if test="${item.id==it.column_id}">checked</c:if>> <label for="column_id${i.count}">${item.name}</label>
	</div>
</c:forEach>


												</div>
											</div>
											<!-- radio end -->
											<div class="form-group">
												<label for="title" class="col-sm-2 control-label">文章标题</label>
												<div class="col-sm-10">
													<input type="text" class="form-control" id="title"
														name="title" placeholder="文章的标题" value="${it.title}">
												</div>
											</div>
											<div class="form-group d_t_dater">
												<label for="toptill_date" class="col-sm-2 control-label">置顶到期</label>
												<div class="col-sm-10">
													<div class="input-group">
														<span class="input-group-addon" style="cursor: pointer;"
															onclick="$.jeDate('#toptill_date',{trigger:false,format: 'YYYY-MM-DD hh:mm:ss'})">置顶到期时间</span>
														<input placeholder="置顶到期时间" type="text"
															class="form-control" id="toptill_date"
															name="toptill_date"
															<c:if test="${it.toptill != 0}">
	value="<fmt:formatDate pattern='yyyy-MM-dd HH:mm:ss' value='${it.toptill_date}' />"
	</c:if>
															readonly>
													</div>
												</div>
											</div>
											<div class="form-group">
												<label for="face_img" class="col-sm-2 control-label">封面图片</label>
												<div class="col-sm-10">
													<input type="hidden" id="faceimage" name="faceimage"
														value="${it.faceimage}" /> <img id="faceimage2"
														src="${it.faceimage}" alt="" width="100" /> <input
														type="button" id="face_img_btn" value="点击选择封面图片" />（请在已经上传的图片空间中选择，无需指定大小和其他设置！）
												</div>
											</div>
											<div class="form-group">
												<label for="author" class="col-sm-2 control-label">作者</label>
												<div class="col-sm-10">
													<input type="text" class="form-control" id="author"
														name="author" placeholder="作者" value="${it.author}">
												</div>
											</div>
											<div class="form-group">
												<label for="content" class="col-sm-2 control-label">文章内容</label>
												<div class="col-sm-10">
													<textarea class="form-control" id="content" name="content"
														style="width: 100%; height: 400px; visibility: hidden;">${it.content}</textarea>
												</div>
											</div>
											<div class="form-group">
												<div class="col-sm-offset-2 col-sm-10">
													<button type="submit" class="btn btn-success">更新文章</button>
												</div>
											</div>
										</form>
									</div>
								</div>
							</div>
						</div>
					</c:when>
				</c:choose>
				<!-- content end -->
				<jsp:include page="../inc/bsa_foot.jsp"></jsp:include>
			</div>
			<!-- /. PAGE INNER  -->
		</div>
	</div>
	<c:if test="${operate != null}">
		<script type="text/javascript" src="bssets/js/uploadheadimg.js"></script>
		<script type="text/javascript" src="bssets/jedate/jquery.jedate.js"></script>
		<script type="text/javascript">
			$(document).ready(function() {
				//------------
				$("#create_gmt_date").jeDate({
					format : "YYYY-MM-DD hh:mm:ss"
				});
				$("#update_gmt_date").jeDate({
					format : "YYYY-MM-DD hh:mm:ss"
				});
				//------------
				$("#form1").submit(function(e) {

					if ($("#title").val() == '') {
						alert("文章标题必须输入！");
						$("#title").focus();
						return false;
					}
					if ($("#author").val() == '') {
						alert("作者必须输入！");
						$("#author").focus();
						return false;
					}
				});
			});
			KindEditor
					.ready(function(K) {
						var editor1 = K
								.create(
										'textarea[name="content"]',
										{
											cssPath : '${basePath}bssets/ket/plugins/code/prettify.css',
											uploadJson : '${basePath}superadmin/uploadfile',
											fileManagerJson : '${basePath}superadmin/filemanager',
											allowFileManager : true,
											afterCreate : function() {
											}
										});
						K('#face_img_btn').click(
								function() {
									editor1.loadPlugin('image', function() {
										editor1.plugin.imageDialog({
											showLocal : false,
											imageUrl : K('#faceimage').val(),
											clickFn : function(url, title,
													width, height, border,
													align) {
												K('#faceimage').val(url);
												K('#faceimage2').attr('src',
														url);
												editor1.hideDialog();
											}
										});
									});
								});
					});
		</script>
	</c:if>
	<c:if test="${operate == null}">
		<script type="text/javascript">
			//搜索框
			$("#searchbtn")
					.click(
							function() {
								var kw = $.trim($("#kw").val());
								var qs = "";
								var and = "?";
								var column_id = "";
								$(
										'input:checkbox[class=column_id_ck]:checked')
										.each(
												function(k) {
													if (k == 0) {
														column_id = $(this)
																.val();
													} else {
														column_id += ','
																+ $(this).val();
													}
												});
								// alert('column_id=' + column_id);
								if (column_id != '') {
									qs += and + "column_id="
											+ column_id;
									and = "&";
								}
								if (kw != '') {
									qs += and + "kw=" + kw;
									and = "&";
								}
								// alert("qs=" + qs);
								$(location).attr('href',
										'${basePath}${pagename}' + qs);
							});

			$(".members").click(
					function() {
						$(location).attr(
								'href',
								'${basePath}${pagename}?operate=members&id='
										+ $(this).val());
					});
		</script>
	</c:if>

</body>
</html>


