<!------------------------------->
<!---- Generated By Denny(luhox@qq.com), cslite for sm -->
<!---- Remarks: ItemListHTML-->
<!---- Date Generated: 2019-04-07 17:14:58-->
<!------------------------------->
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<c:set var="searchpanel" value="false"></c:set>
<c:set var="uploadfile" value="false"></c:set>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<jsp:include page="../inc/bsa_head.jsp"></jsp:include>
<!-- Custom Styles-->
<link href="bssets/css/bsat1-style.css" rel="stylesheet" />
<title>${pagetitle}-${appName}</title>
</head>
<body>
	<div id="wrapper">
		<jsp:include page="../inc/bsa_navtop.jsp"></jsp:include>
		<!--/. NAV TOP  -->
		<jsp:include page="../inc/bsa_navside.jsp"></jsp:include>
		<!-- /. NAV SIDE  -->
		<div id="page-wrapper">
			<div class="header">
				<h3 class="page-header">
					${pagetitle} <small>${subtitle}</small>
				</h3>
			</div>
			<div id="page-inner">
				<!-- content start -->
				<c:choose>
					<c:when test="${operate == null}">

						<!-- div Tables -->
						<div class="panel panel-default">
							<!--  <div class="panel-heading">${tabletitle}</div> -->
							<div class="row margin-xs">
								<div class="col-xs-12 col-sm-12 col-md-1 col-lg-1">
									<div>
										<a href="${pagename}?operate=add" class="btn btn-primary">新增</a>
									</div>
								</div>
							</div>
							<jsp:include page="../inc/pager.jsp"></jsp:include>
							<!-- div表格  (中大屏幕，表格显示) begin -->

							<!-- Advanced Tables -->
							<div
								class="panel panel-default  visible-md-block visible-lg-block">
								<div class="row">
									<div class="col-md-12">
										<div class="panel-body">
											<div class="table-responsive">
												<table
													class="table table-striped table-bordered table-hover"
													id="dataTables-example">
													<thead>
														<tr class="bg-blue">
															<th>序号</th>
															<th>姓名</th>
															<th>微信名称</th>
															<th>拥有角色</th>
															<th>状态</th>
															<th>是否修改密码</th>
															<th>操作</th>
														</tr>
													</thead>
													<tbody>
														<c:forEach var="it" items="${list}" varStatus="index">
															<tr>
																<td id="t${it.id}"> ${index.count+(pager.current - 1) * pager.size} </td>
																<td>${it.name}
																<br>${it.login_name}</td>
																<td><img width="40" alt="${it.wechat_nickname}"
																	src="${it.wechat_headimgurl}"></td>
																<td>${it.email}</td>
																<td><c:choose>
																		<c:when test="${it.is_actived}">
																			<a
																				href="${basePath}${pagename}?operate=hideitem&id=${it.id}"><img
																				alt="" src="bssets/i/greendot.png"></a>
																		</c:when>
																		<c:when test="${it.is_actived==false}">
																			<a
																				href="${basePath}${pagename}?operate=hideitem&id=${it.id}"><img
																				alt="" src="bssets/i/reddot.png"></a>
																		</c:when>
																	</c:choose></td>
																<td><c:choose>
																		<c:when test="${it.login_password=='modified'}">
																			已经修改
																		</c:when>
																		<c:when test="${it.login_password!='modified'}">
																			尚未修改初始密码
																		</c:when>
																	</c:choose></td>
																<td><shiro:hasRole name="superadmin">
																		<button value="${it.id}"
																			class="edititem btn-sm btn btn-success">编辑</button>
																		<button value="${it.id}"
																			class="deleteitem btn btn-sm btn-danger">删除</button>
																	</shiro:hasRole> <shiro:hasRole name="admin">
																		<a
																			href="${basePath}${pagename}?operate=passwordrecovery&id=${it.id}"
																			class="btn-sm btn btn-success">恢复密码为登录手机号码</a>
																	</shiro:hasRole></td>
															</tr>
														</c:forEach>
													</tbody>
												</table>
											</div>
										</div>
									</div>
								</div>
							</div>
							<!--End Advanced Tables -->
							<!-- div表格  (中大屏幕，表格显示) end -->
							<!-- div表格  (小屏幕，类卡片显示) begin -->
							<div class="panel-body visible-xs-block visible-sm-block">
								<div class="row">
									<c:forEach var="it" items="${list}" varStatus="index">
										<div class="col-xs-12 col-sm-6">
											<div class="row showbd margin-xs">
												<div class="col-xs-12 col-sm-12 bg-primary padding-xs"
													id="t${it.id}">
													<h3>${index.count+(pager.current - 1) * pager.size}</h3>
												</div>
												<div class="clearfix"></div>

												<div class="col-xs-12 col-sm-12">${it.login_name}</div>
												<div class="clearfix"></div>

												<div class="col-xs-12 col-sm-12">${it.name}</div>
												<div class="clearfix"></div>

												<div class="col-xs-12 col-sm-12">${it.qq}</div>
												<div class="clearfix"></div>

												<div class="col-xs-12 col-sm-12">${it.email}</div>
												<div class="clearfix"></div>

												<div class="col-xs-12 col-sm-12">${it.wechat_nickname}</div>
												<div class="clearfix"></div>

												<div class="col-xs-12 col-sm-12">${it.is_actived}</div>
												<div class="clearfix"></div>

												<div class="col-xs-12 col-sm-12">
													<button value="${it.id}" class="edititem btn btn-success">编辑</button>
													<button value="${it.id}" class="deleteitem btn btn-danger">删除</button>
												</div>
											</div>
										</div>
									</c:forEach>
								</div>
							</div>
							<!-- div表格  (小屏幕，类卡片显示) end -->
						</div>
						<!--End div Tables -->
					</c:when>
					<c:when test="${operate == 'add'}">
						<div class="row">
							<div class="col-xs-12">
								<div class="panel panel-default">
									<div class="panel-heading">
										<div class="card-title">
											<div class="title">${formtitle}</div>
										</div>
									</div>
									<div class="panel-body">
										<a class="btn btn-warning" href="${pagename}">放弃保存，直接返回</a>
										<form id="form1" class="form-horizontal" method="post"
											action="${pagename}">
											<input type="hidden" name="operate" value="addform" /> <input
												type="hidden" name="referer" value="${referer}" />

											<!-- 角色复选框 -->
											<div class="form-group">
												<label for="role_id" class="col-sm-2 control-label">角色
												</label>
												<div class="col-sm-10">
													<c:forEach var="item" items="${roleall}" varStatus="i">
														<div
															class="checkbox3 checkbox-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} checkbox-check checkbox-light">
															<input type="checkbox" id="role_id_${i.count}"
																name="role_ids" value="${item.name}"
																<c:if test="${item.alias=='超级管理员'}"> disabled </c:if>>
															<label for="role_id_${i.count}"> ${item.alias} <c:if
																	test="${item.alias=='超级管理员'}"> (超级管理员可不是随便加的哦！) </c:if></label>
														</div>
													</c:forEach>
												</div>
											</div>
											<!-- /角色复选框 -->
											<div class="form-group">
												<label for="login_name" class="col-sm-2 control-label">登录账号</label>
												<div class="col-sm-10">
													<input type="text" class="form-control" id="login_name"
														name="login_name" placeholder="登录账号默认为手机号（必填）">
												</div>
											</div>
											<div class="form-group">
												<label for="name" class="col-sm-2 control-label">真实姓名</label>
												<div class="col-sm-10">
													<input type="text" class="form-control" id="name"
														name="name" placeholder="真实姓名（必填）">
												</div>
											</div>
											<div class="form-group">
												<label for="is_actived" class="col-sm-2 control-label">状态
												</label>
												<div class="col-sm-10">
													<div
														class="checkbox3 checkbox-round checkbox-check checkbox-light">
														<input type="checkbox" id="is_actived" name="is_actived"
															checked> <label for="is_actived">
															选中表示正常，未选中表示已经冻结 </label>
													</div>
												</div>
											</div>
											<div class="form-group">
												<div class="col-sm-offset-2 col-sm-10">
													<button type="submit" class="btn btn-success">添加信息</button>
												</div>
											</div>
										</form>
									</div>
								</div>
							</div>
						</div>
					</c:when>
					<c:when test="${operate == 'edit'}">
						<div class="row">
							<div class="col-xs-12">
								<div class="panel panel-default">
									<div class="panel-heading">
										<div class="card-title">
											<div class="title">${formtitle}</div>
										</div>
									</div>
									<div class="panel-body">
										<a class="btn btn-warning" href="${pagename}">放弃保存，直接返回</a>
										<form id="form1" class="form-horizontal" method="post"
											action="${pagename}">
											<input type="hidden" name="operate" value="editform" /> <input
												type="hidden" name="id" value="${it.id}" /> <input
												type="hidden" name="referer" value="${referer}" />
										
											<!-- 权限复选框 -->
											<div class="form-group">
												<label for="role_id" class="col-sm-2 control-label">角色
												</label>
												<div class="col-sm-10">

													<c:forEach var="item" items="${roleall}" varStatus="i">
														<c:set var="hasthisrole" value="false" />
														<c:forEach var="item2" items="${rolelist}" varStatus="j">
															<c:if test="${item.id==item2.id}">
																<c:set var="hasthisrole" value="true" />
															</c:if>
														</c:forEach>
														<div
															class="checkbox3 checkbox-${tagpostfixlist[i.count%fn:length(tagpostfixlist)]} checkbox-check checkbox-light">
															<input type="checkbox" id="role_id_${i.count}"
																name="role_ids" value="${item.name}"
																<c:if test="${item.alias=='超级管理员'}"> disabled </c:if>
																<c:if test="${hasthisrole=='true'}"> checked </c:if>>
															<label for="role_id_${i.count}"> ${item.alias} <c:if
																	test="${item.alias=='超级管理员'}"> (超级管理员可不是随便加的哦！) </c:if></label>
														</div>
													</c:forEach>
												</div>
											</div>
											<!-- /权限复选框 -->											
											<div class="form-group">
												<label for="login_name" class="col-sm-2 control-label">登录账号</label>
												<div class="col-sm-10">
													<input type="text" class="form-control" id="login_name"
														name="login_name" placeholder="登录账号默认为手机号"
														value="${it.login_name}">
												</div>
											</div>
											<div class="form-group">
												<label for="name" class="col-sm-2 control-label">真实姓名</label>
												<div class="col-sm-10">
													<input type="text" class="form-control" id="name"
														name="name" placeholder="真实姓名" value="${it.name}">
												</div>
											</div>
											<div class="form-group">
												<label for="is_actived" class="col-sm-2 control-label">状态
												</label>
												<div class="col-sm-10">
													<div
														class="checkbox3 checkbox-round checkbox-check checkbox-light">
														<c:choose>
															<c:when test="${it.is_actived == true}">
																<input type="checkbox" id="is_actived" name="is_actived"
																	checked>
															</c:when>
															<c:when test="${it.is_actived == false}">
																<input type="checkbox" id="is_actived" name="is_actived">
															</c:when>
														</c:choose>
														<label for="is_actived"> 选中表示正常，未选中表示已经冻结 </label>
													</div>
												</div>
											</div>
											
											<div class="form-group">
												<div class="col-sm-offset-2 col-sm-10">
													<button type="submit" class="btn btn-success">更新信息</button>
												</div>
											</div>
										</form>
									</div>
								</div>
							</div>
						</div>
					</c:when>
				</c:choose>
				<!-- content end -->
				<jsp:include page="../inc/bsa_foot.jsp"></jsp:include>
			</div>
			<!-- /. PAGE INNER  -->
		</div>
	</div>
	<c:if test="${operate != null}">
		<script type="text/javascript" src="bssets/js/uploadheadimg.js"></script>
		<script type="text/javascript" src="bssets/jedate/jquery.jedate.js"></script>
		<script type="text/javascript">
			$(document).ready(function() {
				//------------
				$("#create_gmt_date").jeDate({
					format : "YYYY-MM-DD hh:mm:ss"
				});
				$("#update_gmt_date").jeDate({
					format : "YYYY-MM-DD hh:mm:ss"
				});
				//------------
				$("#form1").submit(function(e) {
					if ($("#login_name").val() == '') {
						alert("登录账号必须输入！");
						$("#login_name").focus();
						return false;
					}
					if ($("#login_password").val() == '') {
						alert("登录密码必须输入！");
						$("#login_password").focus();
						return false;
					}
					if ($("#name").val() == '') {
						alert("真实姓名必须输入！");
						$("#name").focus();
						return false;
					}
				});
			});
		</script>
	</c:if>
	<c:if test="${operate == null}">
		<script type="text/javascript">
			//搜索框
			$("#searchbtn")
					.click(
							function() {
								var kw = $.trim($("#kw").val());
								var qs = "";
								var and = "?";
								var department_id = "";
								$(
										'input:checkbox[class=department_id_ck]:checked')
										.each(
												function(k) {
													if (k == 0) {
														department_id = $(this)
																.val();
													} else {
														department_id += ','
																+ $(this).val();
													}
												});
								// alert('department_id=' + department_id);
								if (department_id != '') {
									qs += and + "department_id="
											+ department_id;
									and = "&";
								}
								var nation_id = "";
								$('input:checkbox[class=nation_id_ck]:checked')
										.each(
												function(k) {
													if (k == 0) {
														nation_id = $(this)
																.val();
													} else {
														nation_id += ','
																+ $(this).val();
													}
												});
								// alert('nation_id=' + nation_id);
								if (nation_id != '') {
									qs += and + "nation_id=" + nation_id;
									and = "&";
								}
								if (kw != '') {
									qs += and + "kw=" + kw;
									and = "&";
								}
								// alert("qs=" + qs);
								$(location).attr('href',
										'${basePath}${pagename}' + qs);
							});

			$(".members").click(
					function() {
						$(location).attr(
								'href',
								'${basePath}${pagename}?operate=members&id='
										+ $(this).val());
					});
		</script>
	</c:if>

</body>
</html>


