//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- Remarks: service tester
//-- Date Generated: 2020-10-09 10:47:59
//-----------------------------

package tpa.tester;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import java.math.BigDecimal;
import org.junit.Test;
import java.util.Date;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import com.baomidou.mybatisplus.core.conditions.update.UpdateWrapper;
import tpa.entity.Evaluation_ip_record;
import tpa.service.IEvaluation_ip_recordService;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = "classpath:spring/spring-context.xml")
public class TestEvaluation_ip_recordService {
	@Autowired
	@Qualifier("evaluation_ip_recordService")
	private IEvaluation_ip_recordService evaluation_ip_recordsvc;

	@Transactional
	@Test
	@Rollback(true)
	public void testExecute() throws Exception {

		// ---------------增加功能测试-------------------
		Evaluation_ip_record it = new Evaluation_ip_record();
		it.setStudent_id(0);
		it.setSno("mm");
		it.setEvaluation_id(0);
		it.setIp("mm");
		it.setCreate_gmt(new Date().getTime());
		it.setType(0);
		try {
			evaluation_ip_recordsvc.save(it);
		} catch (Exception e) {
			e.printStackTrace();
		}
		// 验证
		Evaluation_ip_record item = evaluation_ip_recordsvc.getById(it.getId());
		System.out.println("it="+it.toString());
		System.out.println("item="+item.toString());
		assertTrue(item.getSno().equals(it.getSno()));

		// ---------------修改功能测试-------------------
		UpdateWrapper<Evaluation_ip_record> ituw = new UpdateWrapper<>();
		ituw.set(Evaluation_ip_record.SNO , "hello!");
		ituw.eq(Evaluation_ip_record.ID , it.getId());		
		boolean itupdate = evaluation_ip_recordsvc.update(ituw);	
		// 验证
		item = evaluation_ip_recordsvc.getById(it.getId());
		assertTrue(item.getSno().equals("hello!"));

		// ---------------删除功能测试-------------------
		evaluation_ip_recordsvc.removeById(it.getId());
		item = evaluation_ip_recordsvc.getById(it.getId());
		assertEquals(item, null);

	}
}
