//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- Remarks: service tester
//-- Date Generated: 2020-10-09 10:47:59
//-----------------------------

package tpa.tester;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import java.math.BigDecimal;
import org.junit.Test;
import java.util.Date;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import com.baomidou.mybatisplus.core.conditions.update.UpdateWrapper;
import tpa.entity.Curriculum;
import tpa.service.ICurriculumService;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = "classpath:spring/spring-context.xml")
public class TestCurriculumService {
	@Autowired
	@Qualifier("curriculumService")
	private ICurriculumService curriculumsvc;

	@Transactional
	@Test
	@Rollback(true)
	public void testExecute() throws Exception {

		// ---------------增加功能测试-------------------
		Curriculum it = new Curriculum();
		it.setSubject_id(0);
		it.setStudent_group_id(0);
		it.setUser_id(0);
		it.setIs_actived(false);
		it.setSemester("mm");
		it.setCreate_gmt(new Date().getTime());
		it.setUpdate_gmt(0l);
		try {
			curriculumsvc.save(it);
		} catch (Exception e) {
			e.printStackTrace();
		}
		// 验证
		Curriculum item = curriculumsvc.getById(it.getId());
		System.out.println("it="+it.toString());
		System.out.println("item="+item.toString());
		assertTrue(item.getSemester().equals(it.getSemester()));

		// ---------------修改功能测试-------------------
		UpdateWrapper<Curriculum> ituw = new UpdateWrapper<>();
		ituw.set(Curriculum.SEMESTER , "hello!");
		ituw.eq(Curriculum.ID , it.getId());		
		boolean itupdate = curriculumsvc.update(ituw);	
		// 验证
		item = curriculumsvc.getById(it.getId());
		assertTrue(item.getSemester().equals("hello!"));

		// ---------------删除功能测试-------------------
		curriculumsvc.removeById(it.getId());
		item = curriculumsvc.getById(it.getId());
		assertEquals(item, null);

	}
}
