//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- Remarks: service tester
//-- Date Generated: 2020-10-09 10:48:00
//-----------------------------

package tpa.tester;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import java.math.BigDecimal;
import org.junit.Test;
import java.util.Date;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import com.baomidou.mybatisplus.core.conditions.update.UpdateWrapper;
import tpa.entity.Syslog;
import tpa.service.ISyslogService;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = "classpath:spring/spring-context.xml")
public class TestSyslogService {
	@Autowired
	@Qualifier("syslogService")
	private ISyslogService syslogsvc;

	@Transactional
	@Test
	@Rollback(true)
	public void testExecute() throws Exception {

		// ---------------增加功能测试-------------------
		Syslog it = new Syslog();
		it.setUser_id(0);
		it.setUser_info("mm");
		it.setUser_ip("mm");
		it.setSpend_time(0);
		it.setRequest_content("mm");
		it.setUrl("mm");
		it.setIs_attack(false);
		it.setCreate_gmt(new Date().getTime());
		try {
			syslogsvc.save(it);
		} catch (Exception e) {
			e.printStackTrace();
		}
		// 验证
		Syslog item = syslogsvc.getById(it.getId());
		System.out.println("it="+it.toString());
		System.out.println("item="+item.toString());
		assertTrue(item.getUser_info().equals(it.getUser_info()));

		// ---------------修改功能测试-------------------
		UpdateWrapper<Syslog> ituw = new UpdateWrapper<>();
		ituw.set(Syslog.USER_INFO , "hello!");
		ituw.eq(Syslog.ID , it.getId());		
		boolean itupdate = syslogsvc.update(ituw);	
		// 验证
		item = syslogsvc.getById(it.getId());
		assertTrue(item.getUser_info().equals("hello!"));

		// ---------------删除功能测试-------------------
		syslogsvc.removeById(it.getId());
		item = syslogsvc.getById(it.getId());
		assertEquals(item, null);

	}
}
