//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- Remarks: service tester
//-- Date Generated: 2020-10-09 10:48:00
//-----------------------------

package tpa.tester;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import java.math.BigDecimal;
import org.junit.Test;
import java.util.Date;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import com.baomidou.mybatisplus.core.conditions.update.UpdateWrapper;
import tpa.entity.User_login_log;
import tpa.service.IUser_login_logService;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = "classpath:spring/spring-context.xml")
public class TestUser_login_logService {
	@Autowired
	@Qualifier("user_login_logService")
	private IUser_login_logService user_login_logsvc;

	@Transactional
	@Test
	@Rollback(true)
	public void testExecute() throws Exception {

		// ---------------增加功能测试-------------------
		User_login_log it = new User_login_log();
		it.setLogin_gmt(0l);
		it.setUser_ip("mm");
		it.setUser_id(0);
		it.setOperating_system("mm");
		it.setBrowser("mm");
		it.setCreate_gmt(new Date().getTime());
		try {
			user_login_logsvc.save(it);
		} catch (Exception e) {
			e.printStackTrace();
		}
		// 验证
		User_login_log item = user_login_logsvc.getById(it.getId());
		System.out.println("it="+it.toString());
		System.out.println("item="+item.toString());
		assertTrue(item.getUser_ip().equals(it.getUser_ip()));

		// ---------------修改功能测试-------------------
		UpdateWrapper<User_login_log> ituw = new UpdateWrapper<>();
		ituw.set(User_login_log.USER_IP , "hello!");
		ituw.eq(User_login_log.ID , it.getId());		
		boolean itupdate = user_login_logsvc.update(ituw);	
		// 验证
		item = user_login_logsvc.getById(it.getId());
		assertTrue(item.getUser_ip().equals("hello!"));

		// ---------------删除功能测试-------------------
		user_login_logsvc.removeById(it.getId());
		item = user_login_logsvc.getById(it.getId());
		assertEquals(item, null);

	}
}
