//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- Remarks: service tester
//-- Date Generated: 2020-10-09 10:48:00
//-----------------------------

package tpa.tester;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import java.math.BigDecimal;
import org.junit.Test;
import java.util.Date;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import com.baomidou.mybatisplus.core.conditions.update.UpdateWrapper;
import tpa.entity.Statistic;
import tpa.service.IStatisticService;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = "classpath:spring/spring-context.xml")
public class TestStatisticService {
	@Autowired
	@Qualifier("statisticService")
	private IStatisticService statisticsvc;

	@Transactional
	@Test
	@Rollback(true)
	public void testExecute() throws Exception {

		// ---------------增加功能测试-------------------
		Statistic it = new Statistic();
		it.setSt_date("mm");
		it.setSt_total(0);
		it.setSt_today(0);
		try {
			statisticsvc.save(it);
		} catch (Exception e) {
			e.printStackTrace();
		}
		// 验证
		Statistic item = statisticsvc.getById(it.getId());
		System.out.println("it="+it.toString());
		System.out.println("item="+item.toString());
		assertTrue(item.getSt_date().equals(it.getSt_date()));

		// ---------------修改功能测试-------------------
		UpdateWrapper<Statistic> ituw = new UpdateWrapper<>();
		ituw.set(Statistic.ST_DATE , "hello!");
		ituw.eq(Statistic.ID , it.getId());		
		boolean itupdate = statisticsvc.update(ituw);	
		// 验证
		item = statisticsvc.getById(it.getId());
		assertTrue(item.getSt_date().equals("hello!"));

		// ---------------删除功能测试-------------------
		statisticsvc.removeById(it.getId());
		item = statisticsvc.getById(it.getId());
		assertEquals(item, null);

	}
}
