//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- Remarks: service tester
//-- Date Generated: 2020-10-09 10:48:00
//-----------------------------

package tpa.tester;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import java.math.BigDecimal;
import org.junit.Test;
import java.util.Date;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import com.baomidou.mybatisplus.core.conditions.update.UpdateWrapper;
import tpa.entity.Student;
import tpa.service.IStudentService;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = "classpath:spring/spring-context.xml")
public class TestStudentService {
	@Autowired
	@Qualifier("studentService")
	private IStudentService studentsvc;

	@Transactional
	@Test
	@Rollback(true)
	public void testExecute() throws Exception {

		// ---------------增加功能测试-------------------
		Student it = new Student();
		it.setSno("2017110601");
		it.setLogin_name("2017110601");
		it.setLogin_name_digest("mm");
		it.setLogin_password("2017110601");
		it.setLogin_password_digest("mm");
		it.setName("程洁莹");
		it.setEmail("chengjieying@qq.com");
		it.setIs_actived(true);
		it.setMobile("mm");
		it.setQq("mm");
		it.setWechat_openid("mm");
		it.setWechat_nickname("mm");
		it.setWechat_headimgurl("mm");
		it.setLogin_method(0);
		it.setClasscode("20171106");
		it.setCreate_gmt(new Date().getTime());
		it.setUpdate_gmt(0l);
		try {
			studentsvc.save(it);
		} catch (Exception e) {
			e.printStackTrace();
		}
		// 验证
		Student item = studentsvc.getById(it.getId());
		System.out.println("it="+it.toString());
		System.out.println("item="+item.toString());
//		assertTrue(item.getSno().equals(it.getSno()));

		// ---------------修改功能测试-------------------
		UpdateWrapper<Student> ituw = new UpdateWrapper<>();
		ituw.set(Student.SNO , "110601");
		ituw.eq(Student.ID , it.getId());
		boolean itupdate = studentsvc.update(ituw);
		// 验证
		item = studentsvc.getById(it.getId());
//		assertTrue(item.getSno().equals("hello!"));

		// ---------------删除功能测试-------------------
		studentsvc.removeById(it.getId());
		item = studentsvc.getById(it.getId());
		assertEquals(item, null);

	}

	/**
	 *	julius测试
	 * @throws Exception
	 */
	@Transactional
	@Test
	@Rollback(true)
	public void testExecute1() throws Exception {

		// ---------------增加功能测试-------------------
		Student it = new Student();
		it.setSno("2017110601");
		it.setLogin_name("2017110601");
		it.setLogin_name_digest("mm");
		it.setLogin_password("2017110601");
		it.setLogin_password_digest("mm");
		it.setName("程洁莹");
		it.setEmail("chengjieying@qq.com");
		it.setIs_actived(true);
		it.setMobile("mm");
		it.setQq("mm");
		it.setWechat_openid("mm");
		it.setWechat_nickname("mm");
		it.setWechat_headimgurl("mm");
		it.setLogin_method(0);
		it.setClasscode("20171106");
		it.setCreate_gmt(new Date().getTime());
		it.setUpdate_gmt(0l);
		try {
			studentsvc.save(it);
		} catch (Exception e) {
			e.printStackTrace();
		}
		// 验证
		Student item = studentsvc.getById(it.getId());
		System.out.println("it="+it.toString());
		System.out.println("item="+item.toString());
		assertTrue(item.getSno().equals(it.getSno()));

		// ---------------修改功能测试-------------------
		UpdateWrapper<Student> ituw = new UpdateWrapper<>();
		ituw.set(Student.SNO , "110601");
		ituw.eq(Student.ID , it.getId());
		boolean itupdate = studentsvc.update(ituw);
		// 验证
		item = studentsvc.getById(it.getId());
		assertTrue(item.getSno().equals("hello!"));

		// ---------------删除功能测试-------------------
		studentsvc.removeById(it.getId());
		item = studentsvc.getById(it.getId());
		assertEquals(item, null);

	}
}
