//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- Remarks: service tester
//-- Date Generated: 2020-10-09 10:48:00
//-----------------------------

package tpa.tester;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import java.math.BigDecimal;
import org.junit.Test;
import java.util.Date;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import com.baomidou.mybatisplus.core.conditions.update.UpdateWrapper;
import tpa.entity.Permit;
import tpa.service.IPermitService;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = "classpath:spring/spring-context.xml")
public class TestPermitService {
	@Autowired
	@Qualifier("permitService")
	private IPermitService permitsvc;

	@Transactional
	@Test
	@Rollback(true)
	public void testExecute() throws Exception {

		// ---------------增加功能测试-------------------
		Permit it = new Permit();
		it.setTarget("mm");
		it.setOperation("mm");
		it.setName("mm");
		it.setCode("mm");
		it.setCreate_userid(0);
		it.setUpdate_userid(0);
		it.setCreate_gmt(new Date().getTime());
		it.setUpdate_gmt(0l);
		try {
			permitsvc.save(it);
		} catch (Exception e) {
			e.printStackTrace();
		}
		// 验证
		Permit item = permitsvc.getById(it.getId());
		System.out.println("it="+it.toString());
		System.out.println("item="+item.toString());
		assertTrue(item.getTarget().equals(it.getTarget()));

		// ---------------修改功能测试-------------------
		UpdateWrapper<Permit> ituw = new UpdateWrapper<>();
		ituw.set(Permit.TARGET , "hello!");
		ituw.eq(Permit.ID , it.getId());		
		boolean itupdate = permitsvc.update(ituw);	
		// 验证
		item = permitsvc.getById(it.getId());
		assertTrue(item.getTarget().equals("hello!"));

		// ---------------删除功能测试-------------------
		permitsvc.removeById(it.getId());
		item = permitsvc.getById(it.getId());
		assertEquals(item, null);

	}
}
