//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- Remarks: service tester
//-- Date Generated: 2020-10-09 10:48:00
//-----------------------------

package tpa.tester;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import java.math.BigDecimal;
import org.junit.Test;
import java.util.Date;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import com.baomidou.mybatisplus.core.conditions.update.UpdateWrapper;
import tpa.entity.User;
import tpa.service.IUserService;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = "classpath:spring/spring-context.xml")
public class TestUserService {
	@Autowired
	@Qualifier("userService")
	private IUserService usersvc;

	@Transactional
	@Test
	@Rollback(true)
	public void testExecute() throws Exception {

		// ---------------增加功能测试-------------------
		User it = new User();
		it.setName("mm");
		it.setLogin_name("mm");
		it.setLogin_name_digest("mm");
		it.setLogin_password("mm");
		it.setLogin_password_digest("mm");
		it.setEmail("mm");
		it.setIs_actived(false);
		it.setTelephone("mm");
		it.setQq("mm");
		it.setWechat_openid("mm");
		it.setWechat_nickname("mm");
		it.setWechat_headimgurl("mm");
		it.setLogin_method(0);
		it.setCreate_userid(0);
		it.setUpdate_userid(0);
		it.setCreate_gmt(new Date().getTime());
		it.setUpdate_gmt(0l);
		try {
			usersvc.save(it);
		} catch (Exception e) {
			e.printStackTrace();
		}
		// 验证
		User item = usersvc.getById(it.getId());
		System.out.println("it="+it.toString());
		System.out.println("item="+item.toString());
		assertTrue(item.getName().equals(it.getName()));

		// ---------------修改功能测试-------------------
		UpdateWrapper<User> ituw = new UpdateWrapper<>();
		ituw.set(User.NAME , "hello!");
		ituw.eq(User.ID , it.getId());		
		boolean itupdate = usersvc.update(ituw);	
		// 验证
		item = usersvc.getById(it.getId());
		assertTrue(item.getName().equals("hello!"));

		// ---------------删除功能测试-------------------
		usersvc.removeById(it.getId());
		item = usersvc.getById(it.getId());
		assertEquals(item, null);

	}
}
