//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- Remarks: service tester
//-- Date Generated: 2020-10-09 10:47:59
//-----------------------------

package tpa.tester;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import java.math.BigDecimal;
import org.junit.Test;
import java.util.Date;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import com.baomidou.mybatisplus.core.conditions.update.UpdateWrapper;
import tpa.entity.Experiment_record;
import tpa.service.IExperiment_recordService;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = "classpath:spring/spring-context.xml")
public class TestExperiment_recordService {
	@Autowired
	@Qualifier("experiment_recordService")
	private IExperiment_recordService experiment_recordsvc;

	@Transactional
	@Test
	@Rollback(true)
	public void testExecute() throws Exception {

		// ---------------增加功能测试-------------------
		Experiment_record it = new Experiment_record();
		it.setStudent_id(0);
		it.setSno("mm");
		it.setExperiment_id(0);
		it.setComment("mm");
		it.setMainflow("mm");
		it.setReport("mm");
		it.setResult("mm");
		it.setScore(0);
		it.setSubmit(0l);
		it.setScorescript("mm");
		it.setReviewstate(0);
		it.setCreate_gmt(new Date().getTime());
		it.setUpdate_gmt(0l);
		try {
			experiment_recordsvc.save(it);
		} catch (Exception e) {
			e.printStackTrace();
		}
		// 验证
		Experiment_record item = experiment_recordsvc.getById(it.getId());
		System.out.println("it="+it.toString());
		System.out.println("item="+item.toString());
		assertTrue(item.getSno().equals(it.getSno()));

		// ---------------修改功能测试-------------------
		UpdateWrapper<Experiment_record> ituw = new UpdateWrapper<>();
		ituw.set(Experiment_record.SNO , "hello!");
		ituw.eq(Experiment_record.ID , it.getId());		
		boolean itupdate = experiment_recordsvc.update(ituw);	
		// 验证
		item = experiment_recordsvc.getById(it.getId());
		assertTrue(item.getSno().equals("hello!"));

		// ---------------删除功能测试-------------------
		experiment_recordsvc.removeById(it.getId());
		item = experiment_recordsvc.getById(it.getId());
		assertEquals(item, null);

	}
}
