//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- Remarks: service tester
//-- Date Generated: 2020-10-09 10:47:59
//-----------------------------

package tpa.tester;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import java.math.BigDecimal;
import org.junit.Test;
import java.util.Date;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import com.baomidou.mybatisplus.core.conditions.update.UpdateWrapper;
import tpa.entity.Evaluation_type;
import tpa.service.IEvaluation_typeService;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = "classpath:spring/spring-context.xml")
public class TestEvaluation_typeService {
	@Autowired
	@Qualifier("evaluation_typeService")
	private IEvaluation_typeService evaluation_typesvc;

	@Transactional
	@Test
	@Rollback(true)
	public void testExecute() throws Exception {

		// ---------------增加功能测试-------------------
		Evaluation_type it = new Evaluation_type();
		it.setName("mm");
		try {
			evaluation_typesvc.save(it);
		} catch (Exception e) {
			e.printStackTrace();
		}
		// 验证
		Evaluation_type item = evaluation_typesvc.getById(it.getId());
		System.out.println("it="+it.toString());
		System.out.println("item="+item.toString());
		assertTrue(item.getName().equals(it.getName()));

		// ---------------修改功能测试-------------------
		UpdateWrapper<Evaluation_type> ituw = new UpdateWrapper<>();
		ituw.set(Evaluation_type.NAME , "hello!");
		ituw.eq(Evaluation_type.ID , it.getId());		
		boolean itupdate = evaluation_typesvc.update(ituw);	
		// 验证
		item = evaluation_typesvc.getById(it.getId());
		assertTrue(item.getName().equals("hello!"));

		// ---------------删除功能测试-------------------
		evaluation_typesvc.removeById(it.getId());
		item = evaluation_typesvc.getById(it.getId());
		assertEquals(item, null);

	}
}
