//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- Remarks: service tester
//-- Date Generated: 2020-10-09 10:48:00
//-----------------------------

package tpa.tester;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import java.math.BigDecimal;
import org.junit.Test;
import java.util.Date;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import com.baomidou.mybatisplus.core.conditions.update.UpdateWrapper;
import tpa.entity.Link_user_role;
import tpa.service.ILink_user_roleService;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = "classpath:spring/spring-context.xml")
public class TestLink_user_roleService {
	@Autowired
	@Qualifier("link_user_roleService")
	private ILink_user_roleService link_user_rolesvc;

	@Transactional
	@Test
	@Rollback(true)
	public void testExecute() throws Exception {

		// ---------------增加功能测试-------------------
		Link_user_role it = new Link_user_role();
		it.setUser_id(0);
		it.setRole_id(0);
		it.setCreate_userid(0);
		it.setUpdate_userid(0);
		it.setCreate_gmt(new Date().getTime());
		it.setUpdate_gmt(0l);
		try {
			link_user_rolesvc.save(it);
		} catch (Exception e) {
			e.printStackTrace();
		}
		// 验证
		Link_user_role item = link_user_rolesvc.getById(it.getId());
		System.out.println("it="+it.toString());
		System.out.println("item="+item.toString());
		assertTrue(item.getUser_id().equals(it.getUser_id()));

		// ---------------修改功能测试-------------------
		UpdateWrapper<Link_user_role> ituw = new UpdateWrapper<>();
		ituw.set(Link_user_role.USER_ID , 99);
		ituw.eq(Link_user_role.ID , it.getId());		
		boolean itupdate = link_user_rolesvc.update(ituw);	
		// 验证
		item = link_user_rolesvc.getById(it.getId());
		assertTrue(item.getUser_id().equals(99));

		// ---------------删除功能测试-------------------
		link_user_rolesvc.removeById(it.getId());
		item = link_user_rolesvc.getById(it.getId());
		assertEquals(item, null);

	}
}
