//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- Remarks: service tester
//-- Date Generated: 2020-10-09 10:48:00
//-----------------------------

package tpa.tester;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import java.math.BigDecimal;
import org.junit.Test;
import java.util.Date;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import com.baomidou.mybatisplus.core.conditions.update.UpdateWrapper;
import tpa.entity.Link_student2group;
import tpa.service.ILink_student2groupService;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = "classpath:spring/spring-context.xml")
public class TestLink_student2groupService {
	@Autowired
	@Qualifier("link_student2groupService")
	private ILink_student2groupService link_student2groupsvc;

	@Transactional
	@Test
	@Rollback(true)
	public void testExecute() throws Exception {

		// ---------------增加功能测试-------------------
		Link_student2group it = new Link_student2group();
		it.setStudent_id(0);
		it.setStudent_group_id(0);
		it.setCreate_gmt(new Date().getTime());
		it.setUpdate_gmt(0l);
		try {
			link_student2groupsvc.save(it);
		} catch (Exception e) {
			e.printStackTrace();
		}
		// 验证
		Link_student2group item = link_student2groupsvc.getById(it.getId());
		System.out.println("it="+it.toString());
		System.out.println("item="+item.toString());
		assertTrue(item.getStudent_id().equals(it.getStudent_id()));

		// ---------------修改功能测试-------------------
		UpdateWrapper<Link_student2group> ituw = new UpdateWrapper<>();
		ituw.set(Link_student2group.STUDENT_ID , 99);
		ituw.eq(Link_student2group.ID , it.getId());		
		boolean itupdate = link_student2groupsvc.update(ituw);	
		// 验证
		item = link_student2groupsvc.getById(it.getId());
		assertTrue(item.getStudent_id().equals(99));

		// ---------------删除功能测试-------------------
		link_student2groupsvc.removeById(it.getId());
		item = link_student2groupsvc.getById(it.getId());
		assertEquals(item, null);

	}
}
