//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- Remarks: service tester
//-- Date Generated: 2020-10-09 10:47:59
//-----------------------------

package tpa.tester;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import java.math.BigDecimal;
import org.junit.Test;
import java.util.Date;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import com.baomidou.mybatisplus.core.conditions.update.UpdateWrapper;
import tpa.entity.Evaluation_point;
import tpa.service.IEvaluation_pointService;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = "classpath:spring/spring-context.xml")
public class TestEvaluation_pointService {
	@Autowired
	@Qualifier("evaluation_pointService")
	private IEvaluation_pointService evaluation_pointsvc;

	@Transactional
	@Test
	@Rollback(true)
	public void testExecute() throws Exception {

		// ---------------增加功能测试-------------------
		Evaluation_point it = new Evaluation_point();
		it.setSubject_id(0);
		it.setIs_actived(false);
		it.setType(0);
		it.setDifficulty(0);
		it.setContent("mm");
		it.setCreate_gmt(new Date().getTime());
		it.setUpdate_gmt(0l);
		try {
			evaluation_pointsvc.save(it);
		} catch (Exception e) {
			e.printStackTrace();
		}
		// 验证
		Evaluation_point item = evaluation_pointsvc.getById(it.getId());
		System.out.println("it="+it.toString());
		System.out.println("item="+item.toString());
		assertTrue(item.getContent().equals(it.getContent()));

		// ---------------修改功能测试-------------------
		UpdateWrapper<Evaluation_point> ituw = new UpdateWrapper<>();
		ituw.set(Evaluation_point.CONTENT , "hello!");
		ituw.eq(Evaluation_point.ID , it.getId());		
		boolean itupdate = evaluation_pointsvc.update(ituw);	
		// 验证
		item = evaluation_pointsvc.getById(it.getId());
		assertTrue(item.getContent().equals("hello!"));

		// ---------------删除功能测试-------------------
		evaluation_pointsvc.removeById(it.getId());
		item = evaluation_pointsvc.getById(it.getId());
		assertEquals(item, null);

	}
}
