//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- Remarks: service tester
//-- Date Generated: 2020-10-09 10:47:59
//-----------------------------

package tpa.tester;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import java.math.BigDecimal;
import org.junit.Test;
import java.util.Date;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import com.baomidou.mybatisplus.core.conditions.update.UpdateWrapper;
import tpa.entity.Evaluation_result;
import tpa.service.IEvaluation_resultService;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = "classpath:spring/spring-context.xml")
public class TestEvaluation_resultService {
	@Autowired
	@Qualifier("evaluation_resultService")
	private IEvaluation_resultService evaluation_resultsvc;

	@Transactional
	@Test
	@Rollback(true)
	public void testExecute() throws Exception {

		// ---------------增加功能测试-------------------
		Evaluation_result it = new Evaluation_result();
		it.setStudent_id(0);
		it.setEvaluation_id(0);
		it.setSno("mm");
		it.setComment("mm");
		it.setEvaluation_record("mm");
		it.setScore(0);
		it.setSubmit_gmt(0l);
		it.setIs_reviewed(false);
		it.setCreate_gmt(new Date().getTime());
		it.setUpdate_gmt(0l);
		try {
			evaluation_resultsvc.save(it);
		} catch (Exception e) {
			e.printStackTrace();
		}
		// 验证
		Evaluation_result item = evaluation_resultsvc.getById(it.getId());
		System.out.println("it="+it.toString());
		System.out.println("item="+item.toString());
		assertTrue(item.getSno().equals(it.getSno()));

		// ---------------修改功能测试-------------------
		UpdateWrapper<Evaluation_result> ituw = new UpdateWrapper<>();
		ituw.set(Evaluation_result.SNO , "hello!");
		ituw.eq(Evaluation_result.ID , it.getId());		
		boolean itupdate = evaluation_resultsvc.update(ituw);	
		// 验证
		item = evaluation_resultsvc.getById(it.getId());
		assertTrue(item.getSno().equals("hello!"));

		// ---------------删除功能测试-------------------
		evaluation_resultsvc.removeById(it.getId());
		item = evaluation_resultsvc.getById(it.getId());
		assertEquals(item, null);

	}
}
