//-----------------------------
//-- Generated By Denny(luhox@qq.com)
//-- Remarks: service tester
//-- Date Generated: 2020-10-09 10:47:59
//-----------------------------

package tpa.tester;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import java.math.BigDecimal;
import org.junit.Test;
import java.util.Date;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import com.baomidou.mybatisplus.core.conditions.update.UpdateWrapper;
import tpa.entity.Evaluation;
import tpa.service.IEvaluationService;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = "classpath:spring/spring-context.xml")
public class TestEvaluationService {
	@Autowired
	@Qualifier("evaluationService")
	private IEvaluationService evaluationsvc;

	@Transactional
	@Test
	@Rollback(true)
	public void testExecute() throws Exception {

		// ---------------增加功能测试-------------------
		Evaluation it = new Evaluation();
		it.setCurriculum_id(0);
		it.setIs_actived(false);
		it.setBegin_gmt(0l);
		it.setEnd_gmt(0l);
		it.setContent("mm");
		it.setTitle("mm");
		it.setSortid(0);
		it.setCreate_gmt(new Date().getTime());
		it.setUpdate_gmt(0l);
		try {
			evaluationsvc.save(it);
		} catch (Exception e) {
			e.printStackTrace();
		}
		// 验证
		Evaluation item = evaluationsvc.getById(it.getId());
		System.out.println("it="+it.toString());
		System.out.println("item="+item.toString());
		assertTrue(item.getContent().equals(it.getContent()));

		// ---------------修改功能测试-------------------
		UpdateWrapper<Evaluation> ituw = new UpdateWrapper<>();
		ituw.set(Evaluation.CONTENT , "hello!");
		ituw.eq(Evaluation.ID , it.getId());		
		boolean itupdate = evaluationsvc.update(ituw);	
		// 验证
		item = evaluationsvc.getById(it.getId());
		assertTrue(item.getContent().equals("hello!"));

		// ---------------删除功能测试-------------------
		evaluationsvc.removeById(it.getId());
		item = evaluationsvc.getById(it.getId());
		assertEquals(item, null);

	}
}
